src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/main/java/net/snowflake/ingest/connection/SecurityManager.java
src/main/java/net/snowflake/ingest/example/SnowflakeIngestBasicExample.java
src/main/java/net/snowflake/ingest/utils/ThreadFactoryUtil.java

Added support for SecurityManager to spawn daemon threads so as to not prevent application from shutting down safely.

SimpleIngestManager should not prevent safe shutdown of application

---

deploy.sh
pom.xml
public_pom.xml
scripts/get_project_info_from_pom.py
scripts/update_project_version.py

setup public_pom.xml for release

---

pom.xml
scripts/check_content.sh

shade org.jose4 lib
add shade checker script
fix jar file name to snowflake-ingest-sdk.jar

shade org.jose4 lib

---

pom.xml
src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/connection/SecurityManager.java

Change jwt library to use nimbudus, which is same as the library used in JDBC and server side.

Change jwt library to resolve security vulnerbility. 

---

README.rst
pom.xml
scripts/check_content.sh
src/main/java/net/snowflake/ingest/connection/IngestResponse.java
src/main/java/net/snowflake/ingest/connection/ServiceResponseHandler.java
src/test/java/net/snowflake/ingest/SimpleIngestIT.java
src/test/java/net/snowflake/ingest/TestUtils.java

Fixes: https://github.com/snowflakedb/snowflake-ingest-java/issues/11

Modify IngestResponse POJO to support responseCode and avoid null returns

---

src/main/java/net/snowflake/ingest/connection/HistoryResponse.java

ingestManager.getHistory.getLastInsertTime returns a date, it should return a timestamp.

SNOW-153193 snowflake-ingest-java bug fix

---

deploy.sh
scripts/run_whitesource.sh

https://travis-ci.org/github/snowflakedb/snowflake-ingest-python/jobs/701452011
This run doesnt run with master-baseline. Quick fix to check if project name was set as prod branch or not.

Fix wss script and revert deploy script change

---

.github/workflows/semgrep.yml
.semgrep.yml

soumitr has updated the semgrep name and rule pack, it need to be updated in the PR

update semgrep name and rule pack

---

pom.xml

New version: 
- Improved logging
- Add retries in the client for NoHttpResponseException
SNOW-195017

Bump up the patch in semantic versioning

---

.github/workflows/End2EndTest.yml
src/main/java/net/snowflake/ingest/connection/SecurityManager.java
src/test/java/net/snowflake/ingest/connection/SecurityManagerTest.java

Trim account name if it contains a '.'

---

pom.xml

Update scope for slf4j-simple

---

src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/connection/HistoryRangeResponse.java
src/main/java/net/snowflake/ingest/connection/HistoryResponse.java
src/main/java/net/snowflake/ingest/connection/IngestResponse.java
src/main/java/net/snowflake/ingest/connection/IngestResponseException.java
src/main/java/net/snowflake/ingest/connection/IngestStatus.java
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/main/java/net/snowflake/ingest/connection/SecurityManager.java
src/main/java/net/snowflake/ingest/connection/ServiceResponseHandler.java
src/main/java/net/snowflake/ingest/example/IngestExampleHelper.java
src/main/java/net/snowflake/ingest/example/SnowflakeIngestBasicExample.java
src/main/java/net/snowflake/ingest/utils/BackOffException.java
src/main/java/net/snowflake/ingest/utils/Cryptor.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/main/java/net/snowflake/ingest/utils/RingBuffer.java
src/main/java/net/snowflake/ingest/utils/StagedFileWrapper.java
src/main/java/net/snowflake/ingest/utils/ThreadFactoryUtil.java
src/test/java/net/snowflake/ingest/SimpleIngestIT.java
src/test/java/net/snowflake/ingest/TestUtils.java
src/test/java/net/snowflake/ingest/connection/SecurityManagerTest.java
src/test/java/net/snowflake/ingest/connection/TestKeyRenewal.java

Enable Google Java Format

---

.github/workflows/GoogleJavaFormat.yml

SNOW-331292 Add GoogleJavaFormat as a GH Action
Runs on pushes to master and all PRs

SNOW-331292 Add GoogleJavaFormat as a GH Action

---

src/main/java/net/snowflake/ingest/example/SnowflakeIngestBasicExample.java

The Google Java Format check is added and it's complaining about this particular file, I just run the reformat again and see if we can pass the check

Enable Google Java Format cont.

---

scripts/check_content.sh
src/main/java/net/snowflake/ingest/example/SnowflakeIngestBasicExample.java

Fix mvn install failure to include com/sun in check_content.sh

Fix mvn install failure

---

pom.xml
src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/main/java/net/snowflake/ingest/utils/StringsUtils.java

Remove guava dependency

---

README.md
src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/connection/ClientStatusResponse.java
src/main/java/net/snowflake/ingest/connection/ConfigureClientResponse.java
src/main/java/net/snowflake/ingest/connection/HistoryResponse.java
src/main/java/net/snowflake/ingest/connection/IngestResponseException.java
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/main/java/net/snowflake/ingest/connection/ServiceResponseHandler.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/test/java/net/snowflake/ingest/SimpleIngestIT.java
src/test/java/net/snowflake/ingest/TestUtils.java

Make changes to Ingest SDK for both post api client/configure and get api client/status

SNOW-500221 Client Api SDK changes

---

src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/connection/ClientStatusResponse.java
src/main/java/net/snowflake/ingest/connection/ConfigureClientResponse.java
src/main/java/net/snowflake/ingest/connection/InsertFilesClientInfo.java
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/test/java/net/snowflake/ingest/SimpleIngestIT.java

- Ignoring the tests for now.
- Verified the tests against dev deployment

Add interface for insertFiles with clientInfo - Along with tests

---

src/main/java/net/snowflake/ingest/connection/InsertFilesClientInfo.java

https://snowflakecomputing.atlassian.net/browse/SNOW-514117

SNOW-514117: Add illegal argument exception for negative client sequencer

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Add a beta tag to denote the Preview feature of Snowpipe Client APIs

Release a beta version of SDK for new Snowpipe APIs

---

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java

Add column nullability info to the field metadatada

Add nullability to the field  metadata

---

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java
src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/utils/Constants.java
src/main/java/net/snowflake/ingest/utils/Utils.java
src/test/java/net/snowflake/ingest/TestUtils.java
src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Moved streaming ingest from using profile.properties to profile.json with existing keys

SNOW-356153 Move streaming ingest to use profile.json

---

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java

Added String Date format parsing using JDBC's parser.  Also added validation for OBJECT type

Validate JSON for Object and String Date parsing

---

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java

Checks for variant and object types exceeding max LOB size

SNOW-534044 validate max object and variant sizes

---

profile.json.example
profileTemplate.properties
src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java
src/main/java/net/snowflake/ingest/utils/Constants.java
src/main/java/net/snowflake/ingest/utils/Utils.java
src/main/resources/net/snowflake/ingest/ingest_error_messages.properties

This is a small follow-up fix on top of https://github.com/snowflakedb/snowflake-ingest-java/pull/112 to correct the behaviors

NO-SNOW: small fixes on configuration file behaviors

---

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/main/java/net/snowflake/ingest/streaming/internal/TimestampWrapper.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Adds support to streaming ingest for TIMESTAMP_TZ columns as well as adds string parsing to TIMESTAMP_NTZ columns

SNOW-535803 Support TIMESTAMP_TZ in streaming ingest

---

pom.xml

Remove security vulnerabilities identified by dependabot and white source

NO-SNOW: update dependency

---

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java
src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClient.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java
src/main/java/net/snowflake/ingest/utils/Pair.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java

GCS PUTs require a signed url for every file

SNOW-540821 Fetch signed url on every put call for gcs

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Release new version of Ingest SDK. 
We will call this 1.0.0-beta

Release version 1.0.0-beta

---

src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java

This one fell through the cracks.  JDBC used to throw an NPE if our credentials expired, but we updated it to through a more descriptive error and need to update our credential refresh logic

SNOW-350701 Refresh credentials on correct error

---

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java

Add correctly encoded min/max info for BINARY type

SNOW-515458 Fix min/max for binary datatype

---

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java

Add row sequencer along with channel sequencer for debugging.

Add row sequencer for debugging

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Release note:
1. Fix EP generation for a few data types
2. A few adjustments to be more conservative on memory consumption
3. Add more logging

Release version 1.0.1-beta

---

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Add support for string Date formats

nosnow- support string date formats

---

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Fixing a NullPointerException when the metrics collection is enabled, hopefully this is the last issue before we could do a new release :)

NO-SNOW: fix regression after the JMX metrics change

---

README.md
src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java

Add steps in README and call `offsetToken` API in Example

no-snow Add readme and call offsetToken API in Example file

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

This release contains a few bug fixes and improvements for Snowpipe Streaming:
1. [Bug Fix] Fix the issue when the account_name has a hyphen
2. [Bug Fix] Fix a `channel.close` timeout issue due to high upload latency
3. [Bug Fix] Fix wrong name separator used to build the file path for different platform like Windows
4. [Bug Fix] Fix the column stats for collated strings, this will require server side fix to be deployed in prod
5. [Bug Fix] Add more debug logging in order to debug a memory exception that comes from the Arrow library
6. [Improvement] Improve the README and EXAMPLE for Snowpipe Streaming
7. [Improvement] Upgrade Apache Arrow library to the latest version

V1.0.2-beta.2 release 

---

src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/test/java/net/snowflake/ingest/SimpleIngestIT.java

This is being approved earlier, just pushing it to master. 
https://github.com/snowflakedb/snowflake-ingest-java/pull/184
- Added a new commit which fixes the bug saw earlier in fidelity's case. 
- Will also fix the exception in KC once release 0.10.4-beta.3 is released

NO-SNOW http connection pooling manager

---

pom.xml
src/test/java/net/snowflake/ingest/SimpleIngestIT.java
src/test/java/net/snowflake/ingest/TestUtils.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Enable streaming ingest integration tests in the github build.  I had to split out the test connection used by the snowpipe and the snowpipe streaming tests since they were stepping on each with session state

Run streaming ingest integration tests on build

---

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

Currently, `StreamingIngestIT` uses a fixed DB name: `TEST_DB = "STREAMING_INGEST_TEST_DB"` that gets recreated for each run. This breaks other concurrent PR CI runs.

@snow SNOW-657206 SteamingIngestIT: add random suffix to DB name to fix concurrent CI runs

---

.pre-commit-config.yaml
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/test/java/net/snowflake/ingest/TestUtils.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/LogicalTypesIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/Provider.java

This is the first commit in a series of commits focusing on comprehensive data type validation. It establishes testing infrastructure and adds tests for BOOLEAN data type.
It also fixes a problem that negative integers were previously evaluated as false.

SNOW-655614 Data type validation: Boolean

---

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetTypeGenerator.java
src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ColumnMetadataBuilder.java
src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ParquetTypeGeneratorTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java

This PR is based on Andrey's Parquet generator in #200. It
- refactors `ParquetRowBuffer.java`
- adds `ParquetTypeGeneratorTest.java`
- adds `ParquetValueParserTest.java`
- refactors `ArrowBufferTest.java`

Add Parquet Tests for the parquet-file-generator

---

pom.xml

follow-up for #280 to fix more parquet dependencies causing vulnerabilities in #286

@snow no-snow Fix more parquet dependencies causing vulnerabilities

---

src/main/java/net/snowflake/ingest/connection/TelemetryService.java

This PR contains two changes on the client telemetry:
- Only send the telemetry when the count is NOT 0
- Update the latency unit to milliseconds

NO-SNOW: fix client telemetry logic

---

src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java

This PR contains two changes:
- Fix the ConcurrentModificationException on the telemetry hashmap, use ConcurrentHashMap instead
- Update the logging for SDK version to INFO from DEBUG

SNOW-705594: fix ConcurrentModificationException on the telemetry hashmap

---

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java

cherry picked https://github.com/snowflakedb/snowflake-ingest-java/commit/0364379d5b2093bcab7edccd55b5a16351740091 as a starting point and fixed the merge conflicts

SNOW-684267 Add column name to data validation error messages

---

README.md
profile.json.example
src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/SemiStructuredIT.java

Snowflake parse_json('') is returning NULL so we should use the same behavior.
Tested with unit tests

SNOW-711338 Convert empty variant strings into Variant column to NULL

---

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java
src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java

This PR makes parquet binary max length consistent with Arrow.

@no-snow fix small parquet binary max length inconsistency with Arrow

---

pom.xml
src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java

original commit: a12afc32e5624e6b7377d871d1e7dc8b201e6ad8

NO-SNOW: revert https://github.com/snowflakedb/snowflake-kafka-connector/pull/546/files as it's causing failure on GCS

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

The 1.0.3-beta release has an issue with GCS, so we have to revert https://github.com/snowflakedb/snowflake-ingest-java/pull/334 and then create a new release on top

V1.0.3-beta.1 release

---

pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

This will be the first non-beta release after v0.10.8 and it contains the support to do Snowpipe Streaming

V1.1.0 release

---

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java
src/main/java/net/snowflake/ingest/streaming/internal/ChannelData.java
src/main/java/net/snowflake/ingest/streaming/internal/RowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/resources/net/snowflake/ingest/ingest_error_messages.properties
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java

This PR removes "Arrow" keyword in non-arrow specific logging and replaces it with Parquet in one place.

SNOW-759237 edit few log lines

---

linkage-checker-exclusion-rules.xml
src/main/java/net/snowflake/ingest/utils/ParameterProvider.java

This diff does the following:
- Removes all linker checker issues
- Fixes a warning about brackets in `ParameterProvider.java`

Build fixes

---

linkage-checker-exclusion-rules.xml
pom.xml
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/StringsIT.java

Fixes snyk issue identified in issue 422

---

pom.xml
src/main/java/net/snowflake/ingest/SimpleIngestManager.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/utils/HttpUtil.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java

This reverts commit ca63c27621f2f143638bde113fcfae4a400d145f.
- This is required for Kafka Connector, corresponding PR: https://github.com/snowflakedb/snowflake-kafka-connector/pull/614
- But also uses JDBC 3.13.25

SNOW-726924 Re-add jvmNonProxy host

---

pom.xml
snapshot_deploy.sh
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Snapshot_deploy.sh file will deploy the latest code to [snapshot repo]( https://nexus.int.snowflakecomputing.com/repository/Snapshots/) every night with help of [jenkins job](https://ci-dev-122.int.snowflakecomputing.com/job/MavenPushSnowpipeJavaSDKSnapshot/). 
Benchmark framework will grab the latest build from snapshot repo and run the tests against the latest master(deployed to snapshot repo)

Dshah snow 801462 snapshotdeploy

---

pom.xml

Remove example main classes from code coverage scanning.

NO-SNOW Exclude examples from code coverage scanning

---

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java
src/main/java/net/snowflake/ingest/utils/ErrorCode.java
src/main/java/net/snowflake/ingest/utils/ParameterProvider.java
src/main/resources/net/snowflake/ingest/ingest_error_messages.properties
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java

This PR enforces the max row limit of 64 MB.

SNOW-720420 Enforce per-row size limits

---

README.md

This PR mentioned min JDBC driver version in the README file.

NO-SNOW Mention minimal JDBC driver version 3.13.30

---

src/main/java/net/snowflake/ingest/streaming/internal/ChannelRegisterStatus.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestResponseCode.java
src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestResponseCodeTest.java

Add status code message as part of the channel status response

@snow SNOW-837436 Streaming ingest: get status code message in channel status response

---

src/test/java/net/snowflake/ingest/SimpleIngestIT.java

- These are causing flakiness, disable now, remove later. https://snowflakecomputing.atlassian.net/browse/SNOW-693813

SNOW-693813 disable client info snowpipe tests, remove later

---

unshaded_snapshot_deploy.sh

Support publishing unshaded snapshot release to Nexus repo

NO-SNOW: Support publishing unshaded snapshot release to Nexus repo

---

README.md

Remove a note about Snowpipe Streaming being in public preview.

Remove Public Preview note

---

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java

Remove comment stating that there is no limit on channel creation.

NO-SNOW Remove wrong documentation

---

pom.xml

Fixes Snyk-detected vulnerability in snappy-java 1.1.10.1.

SNOW-924864 Upgrade snappy-java

---

e2e-jar-test/pom.xml
pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

All the additional changes are done by sorting the pom file, looks like this is added as part of https://github.com/snowflakedb/snowflake-ingest-java/pull/604

V2.0.4 release

---

e2e-jar-test/pom.xml
pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Updated version from 2.1.0 to 2.1.0-SNAPSHOT to support streaming ingest benchmark testing.

updated version

---

src/main/java/net/snowflake/ingest/utils/HttpUtil.java

This PR makes the SDK retry requests that fail with `SocketTimeoutException`.

SNOW-1512935 Retry SocketTimeoutException

---

pom.xml

NO-SNOW Upgrade protobuf package

---

e2e-jar-test/pom.xml
pom.xml
src/test/java/net/snowflake/ingest/connection/UserAgentTest.java

released unshaded version of 2.1.2

v2.1.2-unshaded

---

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java
src/main/java/net/snowflake/ingest/streaming/internal/ChunkMetadata.java
src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java
src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java
src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java
src/main/java/net/snowflake/ingest/streaming/internal/InternalParameterProvider.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java
src/main/java/net/snowflake/ingest/utils/Constants.java
src/main/java/org/apache/parquet/hadoop/BdecParquetWriter.java
src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java
src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java
src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java
src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java

This PR contains logic of ep info generation logic as the Iceberg tables requires different EP info than FDN tables.

SNOW-1673203 EP info generation for new table format

---

src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java

Stacked PR for a fix I found in alec's inprogress changes.
@sfc-gh-alhuang Please add a testcase that uses ImmutableCollections for the structured data type test objects, to catch a regression on this front.

Structured Data Type Fix : Don't mutate the collection passed in by the user in InsertRow

---

src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java
src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java
src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java
src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java
src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetBufferValue.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java
src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java
src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java
src/main/java/net/snowflake/ingest/utils/IcebergDataTypeParser.java
src/main/java/net/snowflake/ingest/utils/Utils.java
src/main/java/org/apache/parquet/hadoop/BdecParquetWriter.java
src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java
src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java
src/test/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParserTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ParquetTypeGeneratorTest.java
src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserAssertionBuilder.java

Support structured data type for Iceberg table including struct, map, and list.

SNOW-1666189 Structured data type support

---

src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java

This PR fix the Iceberg ITs accidentally broke by previous  #891. No behavior change.

Fix Iceberg ITs

---

.github/workflows/End2EndTest.yml
pom.xml
scripts/run_gh_actions.sh
src/test/java/net/snowflake/ingest/IcebergIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergDateTimeIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergLogicalTypesIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergNumericTypesIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStringIT.java
src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java
src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergColumnNamesIT.java

Reverts snowflakedb/snowflake-ingest-java#896

Revert "Introduce Iceberg streaming merge gate"

---

.github/workflows/End2EndTest.yml

External volume is set up in sfctest0 azure account. Introduce Azure merge gate for Iceberg ITs.

Introduce Azure merge gate for Iceberg ITs

---

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
src/test/java/net/snowflake/ingest/streaming/internal/it/SubscopedTokenRefreshIT.java

Add an IT for token expire test against Iceberg tables streaming.

SNOW-1813763 Add IT for token expiry and renewal of Iceberg table

---

e2e-jar-test/pom.xml
pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Release 3.0.1

---

e2e-jar-test/pom.xml
pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Release 3.1.0

---

e2e-jar-test/pom.xml
pom.xml
src/test/java/net/snowflake/ingest/connection/UserAgentTest.java

v3.1.0-unshaded release

---

e2e-jar-test/pom.xml
pom.xml
src/test/java/net/snowflake/ingest/connection/UserAgentTest.java

This reverts commit fb4a0234b87696a2b97e50eb94e040eaa682cb92.
The unshaded PR should not be merged

Revert "v3.1.0-unshaded release (#939)"

---

deploy.sh

The job [MavenPushSnowpipeJavaSDK](https://ci-dev-122.int.snowflakecomputing.com/job/MavenPushSnowpipeJavaSDK/) is failing with connection reset when trying to download the dependencies.
```
00:10:46.955 [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom
00:10:46.973 Feb 21, 2025 4:05:54 AM org.apache.http.impl.execchain.RetryExec execute
00:10:46.973 INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->[https://repo.maven.apache.org:443](https://repo.maven.apache.org/): Connection reset
00:10:46.976 Feb 21, 2025 4:05:54 AM org.apache.http.impl.execchain.RetryExec execute
00:10:46.976 INFO: Retrying request to {s}->[https://repo.maven.apache.org:443](https://repo.maven.apache.org/ …
```

SNOW-1948462: Fix Jenkins job to push artifacts to Maven

---

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java
src/main/java/net/snowflake/ingest/streaming/internal/ChannelCache.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java
src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java

clones: https://github.com/snowflakedb/snowflake-ingest-java/pull/945

Adds richer docstring information to key classes

---

e2e-jar-test/pom.xml
pom.xml
src/main/java/net/snowflake/ingest/connection/RequestBuilder.java

Reverts snowflakedb/snowflake-ingest-java#1037

Revert "V5.0.0 Release"
