snowflakedb/snowflake-ingest-java

pom.xml
When writing kafka connector, it need the latest jdbc driver to build connection using key pair.
=> update jdbc version

.travis.yml, pom.xml
- Fix travis build issue (oracle jdk 8)
- upgrade jackson-databind to 2.9.9.2 for security improvement
=> fix travis build issue and upgrade jackson-databind

src/main/java/net/snowflake/ingest/connection/SecurityManager.java
Logging JWTs is considered a security risk and common practice is to protect tokens like any other credential.
=> Do not log JWT

src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/main/java/net/snowflake/ingest/connection/SecurityManager.java
SNOW-163783
- ScheduledThreadExecutor is not shutdown, causing more threads to being spun up when kafka connector is restarted for rebalancing. 
- Consumers can use try-with-resources or can explicitly call `close()` method during shutdown. 
- Fixes #20
=> Implementing auto-closeable for SimpleIngestManager and SecurityManager

pom.xml
Bumping up version for ingest-java sdk to solve thread leak issue inside Kafka Connector
- Introducing `close()` API for `SimpleIngestManager` which can be used as is or object can be instantiated inside a try-with-resource block since it implements `AutoCloseable`
=> Bump up version to 0.9.9

.github/workflows/semgrep.yml, .semgrep.yml
Semgrep is a command-line tool for static analysis. We can use pre-built or custom rules to enforce code and security standards in codebase. When PR is raised, semgrep will check using the rule defined in .semgrep.yml file to detect potential risky code which causes security flaws.
=> add semgrep check

src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java
SNOW-195017
This PR:
- Improves logging, where requestId was not getting printed. 
- Add retry logic for `NoHttpResponseException`. 
- Decouples the retry logic and serviceUnavailableRetry logic from the client creation.
=> Add retry logic for NoHTTPResponseException and improve logging

pom.xml
SNOW-202934
Getting ClassNotFoundException: net.snowflake.ingest.internal.fasterxml.jackson.core.exc.InputCoercionException
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 17 more
There was an automatic bump up by dependabot. https://github.com/FasterXML/jackson-databind/issues/2511
We need to release this version as well. Will follow up after this change. 
Test: https://travis-ci.org/github/snowflakedb/snowflake-ingest-java/builds/733753169
=> Bump up jackson core and databind libraries

pom.xml
This will not bring the slf4j package into internal package. Shading is not needed for slf4j, it stops clients using the SDK not use their default/custom properties. 
https://maven.apache.org/plugins/maven-shade-plugin/
Test:
Generate a jar and use it on my own sample app. 
`log4j.logger.net.snowflake.ingest.connection=ERROR, <Any Appender>
log4j.additivity.net.snowflake.ingest.connection=false`
=> Disable SL4j shading to enable custom properties

pom.xml, scripts/check_content.sh
remove org/slf4j/ directory because slf4j was removed from previous script.  
Fixed build travis CI: https://travis-ci.org/github/snowflakedb/snowflake-ingest-java/builds/742042037
-- Also bumping up the version.
=> Fix mvn install by fixing shaded jar script check

pom.xml, src/main/java/net/snowflake/ingest/utils/HttpUtil.java
SNOW-260640
Background
- Kafka connector added configuration which allows to setup proxy host. 
- This proxy host can have authentication based on username and password. 
- The proxy host is able to call snowpipe api when there are not user/pwd, but fails to do it if proxy enforces one. 
This change allows snowpipe KC to call snowpipe API from KC cluster with proxy on. 
This is a naive implementation of proxy user/password at the moment since KC implements it at JVM level instead of KC level. 
Because this version is already released in KC, we would tackle this naive implementation first and then set proxy parameter which are unique per kafka connector. 
Future update:
- Instead of fetching it from JVM env, we would like to take it in a request. (SimpleIngestManager ctor)
=> Add http proxy username and password support in httpclient for Kafka Connector

pom.xml, scripts/check_content.sh
Based on: https://semver.org/spec/v2.0.0-rc.1.html
Previous [change](https://github.com/snowflakedb/snowflake-ingest-java/commit/c06b01374dc8f3044e602aa67a71a950e4efc237) does include minor changes in the way http clients are made and is backward compatible hence minor version bump
Release Notes:
- Support for pattern pipes. (Ingest response)
- HttpClient now supports rest proxy with username and password (Required for Kafka connector)
Release Urgency
- High - Blocks https://snowflakecomputing.atlassian.net/browse/SNOW-242554
=> Bump up minor version for ingest sdk

pom.xml
Another one of Shading issue. 
Although I removed shaded jar from relocated (internal) package, slf4j was still part of shaded jar. 
This change, reduces scope of base slf4j to provided and removing implementation (slf4j-simple) from shaded plugin. 
This is what it looks like now:
- KC was not able to use custom log4j properties which used to generate file before 0.9.12 (snowpipe sdk where we release unshaded slf4j jar)
- Priority:
- - Urgent
- Tested local jar in KC and tests are passing. sf.log file is also getting created.
=> Fix slf4j shading

pom.xml
Release notes:
- Fixes issue where JWT token invalid was returned from Snowflake servers when accountNames had `.` in them. 
- We will trim account name's suffix after `.`
- Made it functionally similar to python connector.
=> Bump up Java ingest sdk

README.md
Run into this issue during my setup, so updating the README to make sure others know what to do if they need to run examples in the example folder
The change looks nasty, but the result looks good since I really want to have overline text but it doesn't work with ```
=> Update README to include instructions on running the examples

src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/test/java/net/snowflake/ingest/SimpleIngestIT.java, src/test/java/net/snowflake/ingest/TestUtils.java
**Background:** 
- This is required for Kafka connector. 
- KC will use additionInformation which is passed in by the configuration parameter, we will use this information to differentiate whether a KC is self hosted, confluent hosted or potentially by AWS as MSK. 
**More Info:**
- Modify existing user agent string since that is not matching with current standards.
- We cannot have validation on SDK side since there is no validation for snowpipe dispatcher as of yet (Server side)
- Added test
- Technically you would require the user agent information from only single Snowpipe API (ideally `insertFiles`) since the subsequent calls should all happen from same environment, it can be debatable to just add this into `/insertFiles` endpoint but there is no harm in adding to all requests to be …
=> SNOW-225155 add custom user agent in snowpipe requests

pom.xml
https://snowflakecomputing.atlassian.net/browse/SNOW-241535
https://snowflakecomputing.atlassian.net/browse/SNOW-336964
nimbus-jose-jwt -> json-smart
Removed codecs from http client since they havent bumped up yet and added an explicit version for that. 
`mvn dependency:tree`
=> SNOW-241535 SNOW-336964 Remove vulnerable dependency/bump up

pom.xml, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
- Supporting suffix in user agent for snowpipe APIs. (Will be utilized by Snowflake Kafka connector)
- Can use new SimpleIngestManager constructor. 
- Using new version of nimbus-jose-jwt since older version was vulnerable for security.
=> New version of ingest java sdk

deploy.sh
- Jenkins job for releasing this SDK was failing in last step for whitesource check. (It can still release but says file not found since I changed the file name few months back)
=> Rename file after we used gh actions to pass deploy script

.github/workflows/whitesource-issue.yml, .github/workflows/whitesource.yml, .whitesource
The purpose of the PR is to enable whitesource for github integration to enable new features like alerts in `issues` tab, PR check, auto-fix PR for security vulnerabilities.
=> PRODSEC-1059 integrate whitesource for github

src/main/java/net/snowflake/ingest/utils/HttpUtil.java
Resolves issues related to this [ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-488437). 
Currently, the Java SDK does not timeout on HTTP connections, I added timeout in the RequestConfig.
=> SNOW-488437 Add connection timeout

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
include client name and key during file upload, which will be used for streaming ingest billing
=> SNOW-533760: include client name and key during upload

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClient.java, src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
This PR contains a few changes related to simplify the client interface:
1. Add AutoCloseable support
2. Simplify the logic in `close` so it doesn't check for uncommitted channels anymore, our recommendation should be always close the channel or check for uncommitted rows after using it
=> NO-SNOW: simplify SnowflakeStreamingIngestClient interface 

src/main/java/net/snowflake/ingest/streaming/InsertValidationResponse.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
- Useful to map Kafka offsets with insertErrors so as to send specific records to DLQ. 
- It is possible that rows 1, 5, 9 are bad in on error = continue given 10 rows. 
- We will respond with 0 based indices in insertError.
Included a test.
=> Pass in row index corresponding to input rows in response

src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferStatsTest.java
We were not correctly truncating the max string EP information in most cases
=> SNOW-552292 fix max string ep info when the string is truncated

src/main/java/net/snowflake/ingest/streaming/internal/ParameterProvider.java
Increasing the default throttling threshold to reduce the likelihood of memory issues during high throughput
=> Increase the default throttling threshold

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/Cryptor.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/main/java/net/snowflake/ingest/utils/Utils.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
This PR contains multiple small adjustments/fixes for the Snowpipe Streaming SDK:
1. Always release the allocator first before close, to avoid a memory leak error from the Apache Arrow dependency which might be confusing to customer
2. SNOW-354886 is done, remove the comment in `FileColumnProperties`
3. Adjustment the file name generation logic so the last number should be continuous increasing, instead of having gaps as shown during the KC testing
4. Update some logging to include more information
5. Update MAX_CHUNK_SIZE_IN_BYTES to 32MB and MAX_BLOB_SIZE_IN_BYTES to 512MB, given that we want to have files bigger than 1MB after compression
7. Move ParameterProvider.java to the Utils folder, since this could be used acrossed the SDK
=> NO-SNOW: multiple small adjustments/fixes for Snowpipe Streaming

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
Different test accounts have returned different date string formats.  This makes our test robust against different returned formats
=> SNOW-556588 Make timestamp test more robust

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/Cryptor.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
[SNOW-554959](https://snowflakecomputing.atlassian.net/browse/SNOW-554959)
The decryption happens block-wise on the query side. The block size is 16 bytes for AES/CTR. Hence the SfFile downloads and decrypts file sections aligned to the block size, starting at the beginning of the whole file. The IV is also incremented for each block starting with zero at the beginning of the whole file.
The problem is that the interleaved chunks are not aligned or padded to the block size in the client. The IV starts from zero for each chunk. This breaks the decryption on the query side.
This PR changes the encryption algorithm to use padding to get the file-wide alignment.
The PR also adds block counting starting from the beginning of the file to use it as the IV for each chunk encryption.
The change is …
=> @snow SNOW-554959 Align chunk encryption with block size and count for the whole interleaved file

.github/CODEOWNERS
- Update code owner so the streaming ingest team could be added by default when a PR is opened or an issue is created
- Add myself explicitly for easy PR tracking
=> NO-SNOW: update code owner 

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java
- prints the message on KC if parameter for message code 0024 is not
passed
`retry for getLatestCommittedOffsetToken. Retry no:1, message:Get channel status request failed: {0}.`
- `IngestResponseException` calls super constructor which puts in the detailedMessage used in `e.getMessage()`
=> no-snow fix error message printing

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/utils/Constants.java
File scan code in XP requires encrypted data block alignment. We change the encryption to use PKCS7Padding for that. This causes unclear problems that this type of encryption is not available in some cases, e.g. when we try to build and push release version:
```
java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CTR/PKCS7Padding
```
According to this stackoverflow [thread](https://stackoverflow.com/questions/10193567/java-security-nosuchalgorithmexceptioncannot-find-any-provider-supporting-aes-e), PKCS5Padding is usually used with block size of up to 8 bytes. It should be the same as PKCS7Padding in case of AES with block size of 16 bytes. PKCS5Padding does not cause NoSuchAlgorithmException but the padding does not work as excepted.
A potential solution is to …
=> @snow SNOW-572229 Streaning Ingest: Manual padding of compressed chunk for encryption

src/main/java/net/snowflake/ingest/connection/ServiceResponseHandler.java
- As mentioned in httpclient docs
- https://hc.apache.org/httpcomponents-client-4.5.x/quickstart.html
- https://stackoverflow.com/questions/4775618/httpclient-4-0-1-how-to-release-connection
```
Please note that if response content is not fully consumed the underlying
connection cannot be safely re-used and will be shut down and discarded
by the connection manager.
```
I am also seeing few NoHttpResponseException in existing snowpipe + KC where load is increased. This could be one of the potential reasons, although I don't have a thread dump. 
- no test
- I will push this to master and release a new version on top of `0.10.3`
- I will also send out pr for doing this in other APIs which are not GA
Steps:
1. Push this on top of 0.10.3. 
2. CP this commit on top of master.
3. Do this for …
=> BUG_FIX Consume the response entity to free up connection

src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/connection/ServiceResponseHandler.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtils.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsTest.java
Fixing the bug across all APIs
- Closing the entity. 
- Try with resources for httpResponse. (Closes the response)
TLDR: 
- Same as https://github.com/snowflakedb/snowflake-ingest-java/pull/166
- Without the release bump up but for all APIs. 
- Will also push this to master.
=> Use CloseableHttpClient and consume Entity on all APIs

pom.xml, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
Release note:
- On top of `1.0.2-beta`
- Fix a critical bug in channel.close to avoid wrong result
- Retry HTTP APIs on certain status code returned from SF
=> Release version 1.0.2-beta.1

src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/SimpleIngestIT.java
Adding few configurations for `httpClient` as mentioned here. 
- The default implementation of ConnectionManager has just 20 max connections and 2 max connections per route.
- Adding commit https://github.com/snowflakedb/snowflake-ingest-java/pull/104 on top of 0.10.6 release too.
- Adding a background thread for closingIdleConnections as described in [here](https://hc.apache.org/httpcomponents-client-4.5.x/current/tutorial/html/connmgmt.html#d5e405).
Overall guide for HttpClient
- https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html
=> SNOW-585421 use custom connection pooling manager for Apache httpClient

pom.xml
[Apache Arrow library 7.0.0](https://arrow.apache.org/blog/2022/02/08/7.0.0-release/) and plus now supports VectorSchemaRootAppender with BitVector now, switch to the latest 8.0.0 so we could use VectorSchemaRootAppender to append vector to another vector
=> NO-SNOW: Update Arrow library to 7.0.0 to support VectorSchemaRootAppender

src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelDataTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferStatsTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
Reporting the same min/max string information for collated and non-collated text fields
=> SNOW-608483 fix column stats for collated strings

src/main/java/net/snowflake/ingest/streaming/internal/RegisterService.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java
Found out that it was not retrying while debugging streaming ingest with Client SDK. 
- Existing test which doesnt validate the retry mechanism though! 
- Added a test which checks the retries logic. (Ignored)
=> NO-SNOW check the retry logic with millis instead of ms and seconds

pom.xml, scripts/check_content.sh, src/main/java/net/snowflake/ingest/streaming/internal/ArrowFileWriterWithCompression.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/CustomCompressionCodec.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
[SNOW-612516](https://snowflakecomputing.atlassian.net/browse/SNOW-612516)
The high level problem is that even if the mixed table has 100 columns and a user needs to read only one from a BDEC file, the query scanner will always read and parse the whole file.
The BDEC file format is currently based on the Arrow Stream format (ArrowStreamWriter in Java Arrow client). This means that the arrow record batches are just written into the file with their own schema headers. The XP scan code has to use the same type of stream reader. The problem is that the stream read API does not have random access methods to read individual columns. This results in loading the whole file every time.
FlushService in client currently uses ArrowStreamWriter to write record batches. The Java Arrow library also …
=> @snow SNOW-612516 Streaming ingest: add random file reader to scan single columns, format version 2

src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java
During investigation of the parent issue, we saw that bdec file shortnames look like `l5kkhkwc_HFDUCTv22sdxqQR6lW9nOq9dg5e2aiSnSgo5exuHUqACC_22_144.bdec` while fdn shortnames look like `reyy2e_316685135989106_1_001` . 
In the scenario where the two above files end up in the same EpFile , that EpFile will have `reyy2e_316685135989106_1_001` as its max fdn shortname and `l5kkhkwc_HFDUCTv22sdxqQR6lW9nOq9dg5e2aiSnSgo5exuHUqACC_22_144.bdec` as its min, as they are compared lexicographically. 
When computing the EpFileBucketIndex (e.g. during any pruning phase of any query or DML), we bucketize EpFiles based on their min/max fdnshortnames. To do this we extract the [base36 encoded timestamp](https://snowflakecomputing.atlassian.net/wiki/spaces/EN/pages/2352513187/File+ShortName+Format+and+Usage) …
=> SNOW-593873 SNOW-636695 Round timestamp to seconds when creating blob name

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelCache.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelData.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterService.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
Now our client supports only flushing chunk in Arrow format.
This PR refactors buffering and flushing code to support plugins for other file formats.
It is a prerequisite for introducing support of Parquet file format in #200.
There are 2 major places that are made pluggable to support Parquet along with Arrow:
- `ArrowRowBuffer` is refactored to an abstract format-agnostic interface `RowBuffer`, common things are pulled into `AbstractRowBuffer`
- `FlushService` uses the `RowBuffer` to create an abstract format-agnostic interface `Flusher` to flush the rows into a chunk
`ChannelData` has been generified to hold either Arrow vectors or Parquet buffers in #200.
This triggered a lot of generification of other classes to avoid unsafe casts, better ideas are welcome.
@test tests are refactored …
=> @snow SNOW-633432 Refactor RowBuffer and Flusher API

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StubChunkData.java
This is a follow up for #202 to refactor tests to run with various BDEC format versions.
=> @snow SNOW-633432 Refactor tests to support various BDEC format versions

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java
Type validation for Snowflake data types DATE, TIME, TIMESTAMP_*.
It tries to achieve consistency with the behavior of Snowflake
Worksheets.
* Only limited set of Java data types is accepted
* No longer try to parse the result of Object#toString() call
* Never interpret any input in our code, always delegate the
parsing logic to SnowflakeDateTimeFormat
* Numeric values are not allowed for any column (e.g. int 123)
* Decimal strings are not allowed (e.g. "1663580793.123")
* Numeric strings (e.g. "123") are still allowed because Snowflake
Worksheets also allow them, but they are not documented on the
website and the SDK also should not advertise them.
* Date and timestamp strings cannot be passed into TIME columns
* Time strings cannot be passed into DATE and TIMESTAMP_* columns
* Some …
=> SNOW-655614 Data type validation: Date and Time

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/BinaryIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/StringsIT.java
* Limited types allowed for BINARY: byte[] and hex-encoded string
* Limited types allowed for STRING: String, numbers, boolean and char
* Unified exception handling 
* Added explanations why are values being rejected
* Additional test cases added
=> SNOW-655614 Data type validation: String and Binary

src/main/java/net/snowflake/ingest/streaming/internal/ChannelCache.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/utils/Cryptor.java, src/main/java/net/snowflake/ingest/utils/Utils.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
This PR contains two changes:
1. As part of investigating an encryption related issue, we realize the stacktrace and error message are not captured in log for any encryption related exceptions, so this PR adds that support
2. Add a small message indicates the code path of channel invalidation
=> NO-SNOW: add stacktrace during blob building failure

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/serialization/ByteArraySerializer.java, src/main/java/net/snowflake/ingest/streaming/internal/serialization/ZonedDateTimeSerializer.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/NullIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/SemiStructuredIT.java
More restricted validation of VARIANT, ARRAY AND OBJECT has been implemented:
* Only selected types are allowed 
* String **must** be a valid JSON, otherwise it is rejected 
* i.e. `"foo"` is rejected, but `"\"foo\""` is allowed 
* java primitive data types and their arrays 
* `java.time.*` objects 
* `T[]` if `T` is a valid variant type 
* `List<T>` if `T` is a valid variant type 
* `Map<String, T>` if `T` is a valid variant type
* Custom JSON serialization of `ZonedDateTime` and `byte[]`
* Collections (array, list, map) are recursively validated
* ARRAY: Non-array input is converted into a 1-element array
* OBJECT: Non-object input is rejected
* Due to SNOW-664249, the max allowed limit is reduced by 1KB
* Integration tests for ingesting `null` added
=> SNOW-655614 Data type validation: Semi-structured types

src/main/java/net/snowflake/ingest/utils/HttpUtil.java
* Use double checked locking for HTTP client initialisation. 
* Remove state from `ServiceUnavailableRetryStrategy`
=> SNOW-637237 Thread-safe HTTP client initialisation

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelData.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelFlushContext.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelRuntimeState.java, src/main/java/net/snowflake/ingest/streaming/internal/ChunkMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
[SNOW-657667](https://snowflakecomputing.atlassian.net/browse/SNOW-657667)
clean up refactoring of the circular dependencies:
channel -> buffer -> channel
channel -> chunk data -> channel
this allows to use buffer independently from channel and client, e.g. in tests and test file generator
=> @snow SNOW-657667 Streaming ingest: factor out channel from the buffer

src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java
This PR implements a fix for an issue with binary column values in the Parquet flusher. We were creating a utf-8 String for values with type_name=binary  and for byte arrays (hexadecimal strings) that is wrong.
=> SNOW-696155 fix binary values for Parquet

src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
Since a couple of IT tests are not run with Parquet format as part of merge gates, we want to have the ability to run them internally (in precommits) before merging changes. This can be done be setting the `-DenableParquetTests=true` and `-DtestProfile_path=profile.json` properties.
=> SNOW-703928 add two system properties for IT tests

pom.xml
Hadoop dependencies add custom logging implementation that should be provided by users, not by the library.
The PR excludes logging for the Hadoop dependencies.
=> @snow SNOW-705508 Exclude slf4j-reload4j from Hadoop dep

src/main/java/net/snowflake/ingest/utils/HttpUtil.java
429 responses are going to occasionally happen, the SDK will retry and there is no need to scare the users by logging these events on WARN level.
=> SNOW-706682 Log retry-related messages as INFO

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/StringsIT.java
When TIMESTAMP columns scale is less than 9, fractional part in Arrow is stored with less than 9 digits, which is causing mismatch during scanback. Arrow  expects 9 digits in the fractional part.
=> SNOW-707520 Fix incorrect fractional part calculation of TIMESTAMP

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtils.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
This is the client SDK part of the fix for streams on replicated mixed tables, as described [here](https://docs.google.com/document/d/1MZWhyQznTSinT9ZhKYnOO3UIof2n_qAUWVu1S3qZdaY/edit#heading=h.w6d46ulzf6d2). It will only work for Parquet, as we are not planning to go PuPr with Arrow.
The XP and the GS parts are implemented in these two PRs: https://github.com/snowflakedb/snowflake/pull/80212 (for GS) and https://github.com/snowflakedb/snowflake/pull/80209 (for XP).
=> SNOW-704566 Add filename in Parquet extra MD

src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java
This patch implements more efficient calculation of `SFTimestamp` from supported `java.time.*` objects, without calling `toString` on them and parsing the result.
Users should be advised to pass date/time values either as unix timestamp strings or as `java.time.*` objects. Passing dates as formatted strings requires parsing, which is less efficient.
A simple microbenchmark on my local machine shows ≈19x improvement. Sequentially parsing and validating 10M ZonedDateTime objects took ≈36s with the old approach compared to 1.9s with the new approach.
Additionally, this commit unifies processing of timestamps with and without timezones.
=> SNOW-710401 Avoid datetime parsing wherever possible

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/utils/Constants.java
We're seeing some issue where the build time is high during high throughput case (20 million+ rows) with 10+ parallel channels going into the same table, and the root cause is that the buffer takes longer to transfer ownership and the next buffer already builds up with enough rows, so the file size becomes very big which is causing the compression time to be very high. In longer term, instead of checking the channel size, I think checking the allocator size per table would help this case. CC: @sfc-gh-azagrebin @sfc-gh-gdoci 
In this PR, it contains a few changes to improve the build time:
- Fix a wrong buffer size logic which causes the flush to be scheduled unexpectedly
- Use parallel stream to get the buffer data
- Reduce the channel size limit to schedule the flush faster
=> SNOW-715618: Improve build latency for high throughput case with many channels

pom.xml, src/main/java/net/snowflake/ingest/SimpleIngestManager.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
The JDBC driver was upgraded to 3.13.18 and the HttpUtil code was changed to take into account that a user may need to bypass the proxy by providing the -Dhttp.nonProxyHosts JVM argument
=> [SNOW-726993] Ingest SDK Does Not Honor http.nonProxyHosts JVM Argument

src/test/java/net/snowflake/ingest/SimpleIngestIT.java, src/test/java/net/snowflake/ingest/TestUtils.java
Description
Previously SimpleIngestIT depends on pre-created database SNOWPIPE_SDK_DB. If database got deleted by accident it will cause the integration tests to fail. 
In this PR, we create a new database instead of using the pre-existing database each time when we run SimpleIngestIT.
Testing
Integration Test.
Test with a new database name and a schema name in configuration.
```
"schema": "SNOWPIPE_LOZHANG_TEST_SCHEMA",
"database": "SNOWPIPE_LOZHANG_TEST_DB",
```
The integration test can successfully pass.
=> SNOW-731571 SimpleIngestIT runtime created database

src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
This PR switches the default blob format version from Arrow to Parquet.
=> SNOW-733699 make Parquet the default blob format version instead of Arrow

src/main/java/net/snowflake/ingest/streaming/OpenChannelRequest.java, src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ArrowRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/TimestampWrapper.java, src/test/java/net/snowflake/ingest/streaming/internal/ArrowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java
`SnowflakeDateTimeFormat` has some issues. This PR implements the following changes to our date/time processing:
* We no longer depend on `SnowflakeDateTimeFormat`, custom validation and serialization of date/time values has been implemented. 
* `java.time.OffsetDateTime` is the canonical representation of timestamps in the SDK. 
* The following date/time values are going to be accepted: 
* Types from `java.time` package (`LocalDate`, `LocalDateTime`, `OffsetDateTime`, `ZonedDateTime`, `Instant`, `LocalTime`, `OffsetTime`) 
* Strings in ISO-8601 format such as _2011-12-03T10:15:30+01:00_. We attempt to parse one of the above-mentioned types using the `java.time.format.DateTimeFormatter`. 
* Integer-stored strings
* Input values for `TIMESTAMP_TZ` and `TIMESTAMP_LTZ`, which do not carry …
=> SNOW-711299 New date/time processing

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
This PR remove the dependency on `javax.xml.bind` that we used for hex/encoding decoding. We are going to use commons-codec instead.
PR is based on https://github.com/snowflakedb/snowflake-ingest-java/pull/328.
=> Remove JAXB

src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java
In this PR we try to make better estimates of uncompressed, but encoded data that will be written in Parquet pages. It means taking into consideration extra data/metadata added by Parquet when encoding the values. This can lead to a more timely-accurate decision of when to flush the rows to BDEC files.
Parquet encoding details: https://parquet.apache.org/docs/file-format/data-pages/encodings/
=> SNOW-738614 improve uncompressed size estimate for Parquet row buffers

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java
As a protection against concurrent modifications of the input map,  this PR creates a defensive shallow copy of the map, as well as deep copy of its mutable values (currently only `byte[]` for `BINARY` columns). Concurrent modifications could cause issues like data/metadata mismatch or double counting of `null` values.
For semi-structured types, we accept more mutable values (`List` and `Map`), but for these values we do not calculate min/max EP values, so there is no risk of a mismatch between data and metadata.
=> SNOW-745946 SNOW-735517 Create defensive copy of ingested rows

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/StringsIT.java
Allow surrounding whitespace around string input values for various data types, just like Snowflake Worksheets do.
=> SNOW-749216 Allow leading and trailing whitespace

README.md, src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java, src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClient.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
This PR add Javadocs to user-facing types, which clarify thread-safety guarantees. 
For `SnowflakeStreamingIngestChannel`, the Javadocs previously stated that only one thread may ingest data into the same channel, which is not true because one channel instance can be shared between threads.
This PR also changes the documentation link to PuPr URL.
=> Clarify thread-safety guarantees in Javadoc

src/main/java/net/snowflake/ingest/connection/SecurityManager.java
Combined INFO logging for JWT properties and moved to where the properties are set. Reduced the logging level to DEBUG.
Per this customer issue: https://github.com/snowflakedb/snowflake-kafka-connector/issues/526
=> Reduce info logging around JWT token regeneration

pom.xml
This is to exclude nimbus-jose-jwt from hadoop-common dependency as we already introduces a newer version of nimbus-jose-jwt in direct dependency
=> SNOW-761399: exclude nimbus-jose-jwt from hadoop-common dependency

src/main/java/net/snowflake/ingest/streaming/internal/ColumnMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetTypeGenerator.java, src/test/java/net/snowflake/ingest/streaming/internal/ColumnMetadataBuilder.java, src/test/java/net/snowflake/ingest/streaming/internal/ParquetTypeGeneratorTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
Currently, Parquet file generator does not use Snowflake internal column ordinal.
It uses the column index from the column list that comes from server side.
It works when the table just created because the original ordinals are initially the column indexes.
Nonetheless, this breaks table column evolution (add/drop) because the column ordinal is not the index anymore.
@test
`StreamingIngestIT.testTableColumnEvolution`
the test is disabled until the server side fix is released in 7.10.
=> @snow SNOW-759764 Streaming Ingest Parquet: use Snowflake column ordinal

.github/workflows/End2EndTest.yml, pom.xml, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
This PR adds a new GitHub Actions job `build-windows`, which runs our unit and integration tests on Windows. The job runs in parallel with our existing Linux job, so it shouldn't slow down the overall PR build time. The Windows job only executes tests, it does not check code coverage nor does it execute `check_content.sh`.
=> SNOW-766066 Run tests on Windows

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
This PR fixes a bug for OnErrorOption.Abort for Parquet. There the rows were being added directly into the data buffer and not in the temporary buffer.
=> @no-snow fix bug in OnErrorOption.Abort for Parquet

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetTypeGenerator.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
Calling this Parquet lib method in addRow() turned to be very expensive as its implementation is subotimal, `MessageType#getColumns`:
```
ColumnDescriptor columnDescriptor = schema.getColumns().get(colIndex);
PrimitiveType.PrimitiveTypeName typeName =
columnDescriptor.getPrimitiveType().getPrimitiveTypeName();
```
Instead we can just cache `PrimitiveTypeName` that we derived in setup method in column metadata index.
@test run DEW locally + precommit
=> @snow SNOW-779794 Client SDK Parquet buffer: fix perf degradation due to calling suboptimal lib method per row

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
- Andrey pointed out this. Thanks @sfc-gh-azagrebin 
- There are two indices used - bufferedRowIndex and insertRowIndex. BufferedRow index was not used in parquetBuffer but was used in arrow. insertRowIndex was introduced earlier 1310e0591491647696aeb755d5b4ecbf0d1b1c67 but was incorrectly used in parquet buffer. The index used there was bufferedRowIndex. Since we didnt use the bufferedRowIndex anywhere in parquetBuffer, I replaced it with `insertRowsBuffer`
=> NO-SNOW Fix bug for ParquetRowBuffer regarding row Index

src/main/java/net/snowflake/ingest/streaming/internal/MemoryInfoProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/MemoryInfoProviderFromRuntime.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
The test `SnowflakeStreamingIngestChannelTest#testInsertRowThrottling` is flaky on Windows. The reason is that we are using mockito to mock methods from java.lang.Runtime in one thread and read them in another. These changes are not always guaranteed to be visible in the other thread.
This PR introduces a new interface with two implementations to provide memory info, so we don't need to mock anything anymore.
=> NO-SNOW Fix flaky Windows test

src/test/java/net/snowflake/ingest/streaming/internal/OpenManyChannelsIT.java
The `OpenManyChannelsIT` integration test takes a very long time and generates a large log output. It is not a good fit for SDK integration tests running with each PR and will be re-implemented in dew.
=> SNOW-807102 Disable OpenManyChannelsIT

pom.xml, scripts/check_content.sh, scripts/run_gh_actions.sh
This PR reorganizes our shaded JAR, so that the only top level packages are snowflake ones. All dependencies are shaded into the package `net.snowflake.ingest.internal`.
The script `check_content.sh` has been adapted accordingly, it now only ignores a limited set of required top-level files and directories.
Additionally, this PR removes some unnecessary transitive dependencies, particularly those pulled in by `hadoop-common`.
Tests executed:
* dew tests (both Arrow and Parquet) have passed.
* SDK integration tests have passed. The tests were extracted into a separate maven project and the SDK was added as a dependency, to make sure it tests the shaded JAR.
=> SNOW-801398 Tidy up shaded jar

src/main/java/net/snowflake/ingest/streaming/internal/ArrowFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/ChunkMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java
This PR fixes the uncompressed size that we log. Previously it had an incorrect value for Parquet.
=> SNOW-806047 fix logged uncompressedSize for Parquet

pom.xml
- Please note, this is just upgrading JDBC to 3.13.30, no other changes.
- Required for 
- Future Ingest SDK's support for downscope token. 
- To use 3.13.30 in Kafka Connector. 
- (Issue with shaded library that even after explicitly mentioning the use of 3.13.30 in KC, it still uses 3.13.29 from ingest SDK)
I will push this to master as well push this to a branch on top of 1.1.3
=> NO-SNOW Upgrade JDBC to 3.13.30

pom.xml
This PR reverts relocating `snowflake-jdbc` driver in the shaded JAR. Relocation caused test failures and didn't solve the problem it was supposed to - not having any impact on existing users. Existing users who depended on the JDBC driver without declaring it in their pom.xml, would still see errors.
We should release this change as 2.0.0, so that it is clear from the version number that some dependencies have changes. 
Also, we will be releasing an unshaded variant in every release.
To sum up, the final state is: JDBC driver is not shaded, not relocated, it will be declared as a dependency in the final reduced pom.xml.
=> Revert "SNOW-811371 Shade and Relocate Snowflake JDBC Classes (#494)"

.github/workflows/End2EndTest.yml
Our builds are occasionally failing with the following exception:
```
2023-05-17T14:20:16.7749209Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:analyze-only (analyze) on project snowflake-ingest-sdk: Execution analyze of goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:analyze-only failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-dependency-plugin:jar:3.3.0 -> org.apache.maven.reporting:maven-reporting-impl:jar:3.1.0: Failed to read artifact descriptor for org.apache.maven.reporting:maven-reporting-impl:jar:3.1.0: Could not transfer artifact org.apache.maven.reporting:maven-reporting-impl:pom:3.1.0 …
```
=> Fix 'Connection reset' build errors by caching mvn dependencies

pom.xml, src/main/resources/META-INF/third-party-licenses/Apache2.0.txt, src/main/resources/META-INF/third-party-licenses/BSD-2-Clause.txt, src/main/resources/META-INF/third-party-licenses/BSD-3-Clause.txt, src/main/resources/META-INF/third-party-licenses/EDL1.0.txt, src/main/resources/META-INF/third-party-licenses/Go.txt, src/main/resources/META-INF/third-party-licenses/MIT.txt, src/main/resources/META-INF/third-party-licenses/REVISED_BSD.txt
This PR adds licenses of SDK dependencies to the META-INF directory of the fat jar. In pom.xml, we maintain the list of allowed licenses. In the 'package' build phase, we verify there aren't any new dependencies, not mentioned in the allowed list.
=> SNOW-768197 Attribution notice

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
Server side now supports column ids for Parquet.
Re-enabling column evolution test with enabled change tracking: `StreamingIngestIT.testTableColumnEvolution`.
=> @snow SNOW-763199 Enable StreamingIngestIT.testTableColumnEvolution

src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/test/java/net/snowflake/ingest/connection/UserAgentTest.java
While constructing HTTP User-Agent header, take the SDK version from code instead from a file on classpath. It is less prone to accidental classpath overrides. The consequence of this is that we must now keep the DEFAULT_VERSION in sync with the project version defined in Maven, which we are doing already anyway (a new test has been added to verify this).
=> SNOW-830955 Use default SDK version in User-Agent

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java
This PR introduces enforcement of min and max allowed dates and timestamps. For dates, we allow the range [-9999..9999], for timestamps we allow [1..9999].
=> NO-SNOW Enforce allowed DATE and TIMESTAMP range

src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestResponseCode.java
=> @snow SNOW-837436 Streaming ingest: dedup var for support status code messages

pom.xml
Blackduck scans of Kafka Connector revealed a netty-common vulnerability in 4.1.80.Final. Though we use 4.1.82.Final, lets upgrade to the latest
https://mvnrepository.com/artifact/io.netty/netty-common
=> [SNOW-843760] Upgrade netty-common in response to CVE vulnerability 

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
There is a race condition, which leads to a NPE when one thread invalidates the channel, while another thread is inside of insertRows(). The problem is that channel invalidation clears fieldIndex, which may still be used in threads concurrently inserting rows.
There is no need to clear the fieldIndex during invalidation, it is enough to mark the channel as invalid and it won't be flushed. When channel is reopened, setupSchema() will clear fieldIndex and reinitialize the schema.
=> SNOW-855191 Race condition causing NPE

src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/utils/HttpUtilTest.java
This PR retries SSLException, which we have been seeing in client logs. It additionally evicts idle connections after 60s of inactivity.
=> SNOW-851351 Retry javax.net.ssl.SSLException

src/test/java/net/snowflake/ingest/TestUtils.java
OAuth Test fails when profile path is unspecified. Adding a default scheme parameter to resolve this issue.
See [JIRA ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-870386) for more info.
=> SNOW-870386 Add default scheme parameters for test utils when profile is not specified

src/main/resources/net/snowflake/ingest/ingest_error_messages.properties
According to this [discussion](https://github.com/snowflakedb/snowflake-ingest-java/pull/537#discussion_r1266675618), a complete error translation should be added. Add corresponding error message for the OAuth [PR](https://github.com/snowflakedb/snowflake-ingest-java/pull/537).
=> SNOW-352846 OAuth Authentication: #3 Add error message

src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtils.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsTest.java, src/test/java/net/snowflake/ingest/utils/HttpUtilTest.java
Currently, we have resilient retries when the cause of the error is unavailable service (e.g. 503 or 429 returned from the server side) - we retry every 3 seconds for up to 2 minutes in total. However, when an `IOException` is thrown by the http client, we only retry specific exceptions up to 3 times. This PR makes sure we all retry previously seen `IOException` up to 10x.
This PR should reduce the number of channel invalidations due to incorrect row sequencer (`status_code=21`) as reported in #547.
=> NO-SNOW Retry failed requests more aggressively

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/ChunkMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java
[SNOW-835618](https://snowflakecomputing.atlassian.net/browse/SNOW-835618)
Currently, we send only compressed chunk length in blob metadata.
We can also send uncompressed and log in ingestion events to analyse compression ratio stats.
[SNOW-835618]: https://snowflakecomputing.atlassian.net/browse/SNOW-835618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> @snow SNOW-835618 Snowpipe Streaming: send uncompressed chunk length from SDK to GS

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestBigFilesIT.java
This PR reduces the number of rows in `StreamingIngestBigFilesIT` from 20k to 10k per channel. This will stop server-side alerts on oversized chunks.
=> reduce number of rows in BigFilesIT

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsIT.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsTest.java
`testJWTRetries` required interaction with server side, move it from unit test to IT.
=> Move testJWTRetries test to IT

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/utils/ErrorCode.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/main/resources/net/snowflake/ingest/ingest_error_messages.properties, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
The SDK is currently unable to split the batch passed to insertRows if it is too large. This PR emits a warning if the batch is larger than 16MB and completely rejects the batch if its size is more than 128 MB. Both values are configurable.
=> SNOW-861190 Add warning for large batches in insertRows

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
This PR extracts `enableParquetMemoryOptimization, maxChunkSizeInBytes, maxRowSizeInBytes` into `ClientBufferParameters`, which represents relevant buffer parameters that are set at client level. This is done for more readibility and to make adding new parameters easier.
=> @no-snow refactor a few variables into ClientBufferParameters

src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java
We want to expose a knob that gives users the ability to control when data is ingested. This has a material difference on the size of blobs generated and can result in fewer smaller-sized blobs which in turn affects query performance. The trade-off is higher ingest latencies. We have decided to expose this in the form of an optional `MAX_CLIENT_LAG` option that accepts inputs as the following:
- `number second` (ex: `1 second`)
- `number seconds` (ex: `2 seconds`)
- `number minute` (ex: `1 minute`)
- `number minutes` (ex: `2 minutes`)
By default we use 1 second as the maximum client lag which is the current behavior of the SDK.
Note that this dictates when a flush is triggered to cloud storage. Depending on your connection to cloud storage and cloud storage tail latencies a blob persist …
=> SNOW-914666 Adds MAX_CLIENT_LAG configuration option

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java, src/main/java/net/snowflake/ingest/streaming/internal/ColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
We've had requests to surface the table schema for a channel so that it is possible to reason about what columns need to be supplied to a given call of `insertRow` or `insertRows`. This surfaces a map of Column Name to Column Properties that are normally surfaced in the output of `SHOW COLUMNS`.
@test adds test to `SnowflakeStreamingIngestChannelTest.java`
=> SNOW-919423 Surfaces Table Schema for a Channel

.github/workflows/End2EndTest.yml, README.md, e2e-jar-test/core/pom.xml, e2e-jar-test/core/src/main/java/net/snowflake/IngestTestUtils.java, e2e-jar-test/fips/pom.xml, e2e-jar-test/fips/src/test/java/net/snowflake/FipsIngestE2ETest.java, e2e-jar-test/pom.xml, e2e-jar-test/run_e2e_jar_test.sh, e2e-jar-test/standard/pom.xml, e2e-jar-test/standard/src/test/java/net/snowflake/StandardIngestE2ETest.java, linkage-checker-exclusion-rules.xml, pom.xml, scripts/process_licenses.py, scripts/update_project_version.py, src/main/java/net/snowflake/ingest/utils/ErrorCode.java, src/main/java/net/snowflake/ingest/utils/Utils.java, src/main/resources/net/snowflake/ingest/ingest_error_messages.properties, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/BinaryIT.java
This PR implements support for FIPS-compliant JDBC driver `snowflake-jdbc-fips`, which some users are using instead of the default `snowflake-jdbc`. The difference is that the `snowflake-jdbc` shades bouncy castle, but `snowflake-jdbc-fips` declares FIPS compliant bouncy castle JARs in its `pom.xml`.
The existing SDK versions are not working with `snowflake-jdbc-fips` because they assume that bouncy castle is bundled in the JDBC driver and that `BouncyCastleProvider` exists on classpath, but in case of the FIPS version, the provider class name is `BouncyCastleFipsProvider`.
Documentation has been updated with instructions how to use the SDK in a FIPS-compliant way.
This PR also introduces a new external testing suite - a dedicated maven project, which does not test the SDK from "within" …
=> SNOW-926149 Fix issues while using snowflake-jdbc-fips

README.md
Issue https://github.com/snowflakedb/snowflake-ingest-java/issues/599 
JDBC versions 3.14.0 or higher currently not supported
=> Update readme for JDBC version issues #599

src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ManyTablesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
When one client is ingesting into many tables, we are seeing occasional timeouts from blob registrations calls. This PR introduces the limit of 20 chunks in one blob and in blob registration request.
Fixes #570
Fixes #567
=> SNOW-902709 Limit the max allowed number of chunks in blob

pom.xml
The SDK is exporting an old version of its transitive dependency snappy-java. This is visible in the new `e2e-jar-test` project, which is pulling in `snappy-java` version defined in `hadoop-common` and not the version we define in `dependencyManagement`. This PR makes `snappy-java` a direct runtime dependency, so we can control the version.
=> SNOW-936900 Use upgraded version of snappy-java

e2e-jar-test/pom.xml, pom.xml
This PR resolves the following Snyk findings:
* `bc-fips` - In our e2e-jar-test project we depend on `snowflake-jdbc-fips`, which transitively depends on a vulnerable version of `bc-fips`. We explicitly pull in a newer version. 
* `protobuf-java` - SDK contains vulnerable transitive dependency pull in by `hadoop-common`. This PR marks `protobuf-java` as a direct dependency, so version specified by the SDK will be pulled in. 
Closes #610
Closes #611
Closes #612
Closes #613
Closes #614
Closes #615
Closes #616
Closes #617
Closes #618
Closes #622
Closes #623
Closes #624
Closes #625
=> SNOW-945927 SNOW-945928 Fix Snyk vulnerabilities

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
We need to use a separate variable to store the index in the original batch instead of `tempRowcount`, added a test to verify the behavior
=> NO-SNOW: fix row index issue for ON_ERROR=SKIP_BATCH

src/main/java/net/snowflake/ingest/streaming/OpenChannelRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
Adds an optional offsetToken field to OpenChannelRequest.java which will overwrite existing offset token if provided.
=> SNOW-949967 Add an optional offset token parameter for openChannel

src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/main/java/org/apache/parquet/hadoop/BdecParquetWriter.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
This PR adds support for specifying the compression algorithm to be used for BDEC Parquet files. The allowed value is just `GZIP` for now.
=> SNOW-672156 support specifying compression algorithm to be used for BDEC Parquet files

Jenkinsfile
Add Jenkins script to create TPC-DS 1TB datasets on qa3 and preprod12 using the snowflake-ingest-sdk.
This script is triggered by adding a new tagged release to this repository.
It is used by and uses Jenkins Jobs added in this [jenkins_utils PR](https://github.com/snowflakedb/jenkins_utils/pull/9710)
It needs [this PR](https://github.com/snowflakedb/streaming-ingest-benchmark/pull/8) in the setup application to function for the configured scale factor of 1TB
=> SNOW-964536 benchmark setup

src/main/java/net/snowflake/ingest/streaming/internal/BlobMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java
This PR add a new field `spansMixedTables` in BlobMetadata, which is send in the blob registration request.
This flag will be used server-side for optimizations and sanity checks. 
After this PR, we want to simplify the retry logic so that the new register blob request has all chunks contained in a blob and attempted previously, not just failed chunks.
Both of these will serve the same goal to have correct flag value server-side. The flag is there in case there is something wrong with retries or we have to revert back to old retry logic. 
**I'll wait for the server-side change to be deployed before merging this PR.**
=> SNOW-928922 send spansMixedTables flag in blob registration requests

Jenkinsfile
Description
I accidentally didn't change the database name from the test database to the performance sign-off database
=> SNOW-964536 Fix name of database the dataset is created in

src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/main/java/net/snowflake/ingest/streaming/OpenChannelRequest.java, src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/SimpleIngestIT.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
- After `MAX_CLIENT_LAG` was introduced, it's not backward compatible with the current logic since `MAX_CLIENT_LAG_ENABLED` is true by default and we won't even check for `BUFFER_FLUSH_INTERVAL_IN_MILLIS`. Instead of supporting backward compatible, I decide to remove `BUFFER_FLUSH_INTERVAL_IN_MILLIS` completely since that is an undocumented parameter. We only support `MAX_CLIENT_LAG` going forward and using `BUFFER_FLUSH_INTERVAL_IN_MILLIS` will result in an exception. 
- To match the behavior of `BUFFER_FLUSH_INTERVAL_IN_MILLIS` so the transition is smooth, `MAX_CLIENT_LAG` now also supports LONG input and input without a time unit (default will be milliseconds)
- Some code format changes done automatically by the Google Java Format
- Reenable some tests disabled long time ago
=> NO-SNOW: Deprecate BUFFER_FLUSH_INTERVAL_IN_MILLIS parameter

.github/workflows/End2EndTest.yml, e2e-jar-test/pom.xml
This PR changes the end to end JAR test to run on all clouds. The `snowflake-jdbc-fips` is updated to `3.13.34`, which fixed upload to GCS that was previously failing.
=> NO-SNOW Run e2e jar tests on all clouds

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
We're hitting test failures during snapshot release and the reason is because there's no profile.json file, this PR adds a test mode in SnowflakeStreamingIngestClientFactory so that we can continue use dummyHost name for unit testing.
2024-01-09 23:17:26 testClientFactorySuccess(net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientTest)  Time elapsed: 180.565 sec  <<< ERROR!
2024-01-09 23:17:26 net.snowflake.ingest.utils.SFException: Unable to connect to streaming ingest internal stage.
2024-01-09 23:17:26 	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientTest.testClientFactorySuccess(SnowflakeStreamingIngestClientTest.java:266)
2024-01-09 23:17:26 Caused by: net.snowflake.client.jdbc.internal.apache.http.conn.ConnectTimeoutException: Connect to …
=> NO-SNOW: fix test failures during releasing

src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
Revert https://github.com/snowflakedb/snowflake-ingest-java/commit/2b702db9918f26eaf59a64346bab06462e10186f
This change updates the public API for an internal special use case only which is not ideal, looks like we keep updating public APIs in https://github.com/snowflakedb/snowflake-ingest-java/pull/661 as well. Given that we're still in a POC phase, I suggest we do everything in another branch instead, hence removing this from the next public release and could discuss what's the best way to support this internal use case once the POC is done.
=> NO-SNOW: Revert one change that updates public API for internal use case

e2e-jar-test/core/src/main/java/net/snowflake/IngestTestUtils.java, e2e-jar-test/fips/src/test/java/net/snowflake/FipsIngestE2ETest.java, e2e-jar-test/pom.xml, e2e-jar-test/standard/src/test/java/net/snowflake/StandardIngestE2ETest.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
This PR implements refresh of downscoped GCS tokens. Additionally, it increases the number of retries up to 10 for cloud storage upload errors with exponential backoff. 
Testing: There is a new test in the e2e JAR test project, which runs 80-minute test with both `snowflake-jdbc` and `snowflake-jdbc-fips` during which the token should be refreshed. This test passed successfully ([AWS](https://github.com/snowflakedb/snowflake-ingest-java/actions/runs/7530921751/job/20498349542?pr=665), [Azure](https://github.com/snowflakedb/snowflake-ingest-java/actions/runs/7530921751/job/20498350641?pr=665), [GCP](https://github.com/snowflakedb/snowflake-ingest-java/actions/runs/7530921751/job/20498351333?pr=665)), but it is disabled by default due to its long runtime. Due to SNOW-1009045, `-SNAPSHOTS` …
=> SNOW-995369 GCS token refresh

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java
unescaped usage of > in javadoc threw warning; simple fix
=> NO-SNOW Correct invalid use of javadoc

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestChannel.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/TimestampWrapper.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java
According to https://docs.snowflake.com/en/sql-reference/functions/to_timestamp#usage-notes:
- If the integer is less than 31536000000 (the number of milliseconds in a year), then the value is treated as a number of seconds.
- If the value is greater than or equal to 31536000000 and less than 31536000000000, then the value is treated as milliseconds.
- If the value is greater than or equal to 31536000000000 and less than 31536000000000000, then the value is treated as microseconds.
- If the value is greater than or equal to 31536000000000000, then the value is treated as nanoseconds.
Due to the multiplication logic in the code, we run into an overflow issue when the input is bigger than a certain value (for example: 31535999999999) and it causes **silent corrupted values** in the table, …
=> SNOW-1032874: Fix an Overflow Issue for Integer-store Timestamp 

src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java, src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
This PR sends column ordinals additionally to column names to server side for cross-check of columns in case of table schema changes where columns are recreated with the same name but different data type.
=> Snowpipe Streaming: send column ordinal back to GS with blob EPs to register

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelData.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelMetadata.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
This sends the start and end offset tokens for a channel when sending a blob to Snowflake. Right now only the end offset is sent which makes reasoning about ranges difficult.
@test verified via existing tests in `RowBufferTest` and `SnowflakeStreamingIngestChannelTest`
=> SNOW-967235 Sends start and end offsets from the Client SDK

pom.xml
The linkage checker is failing with Maven 3.9.5.
=> SNOW-1230527 Disable linkage checker

pom.xml
This PR updates dependencies identified by Snyk as vulnerable.
- `common-compress` - The SDK already using the fixed version, but due to Maven bug [MNG-7982](https://issues.apache.org/jira/browse/MNG-7982), the version is not propagated to the e2e test project. This PR declares `common-compress` as a direct dependency to work around the issue.
- `bouncycastle` - the [Snyk-identified vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6277381) doesn't seem to resolved even in the latest BC version, so we just upgrade BC to the latest version, and we will see if the warning disappears.
---
- Fixes #706
- Fixes #707
- Fixes #708
- Fixes #709
- Fixes #710 
- Fixes #711
=> SNOW-1196967 SNOW-1196966 Update vulnerable dependencies

src/main/java/net/snowflake/ingest/streaming/internal/ChannelCache.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/resources/net/snowflake/ingest/ingest_error_messages.properties, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java
When a channel is invalidated, the original SDK does not throw a visible enough error. This PR makes SDK show more specific details for user when `INVALID_CHANNEL` is thrown.
[JIRA](https://snowflakecomputing.atlassian.net/browse/SNOW-1000828)
=> SNOW-1000828 Expose specific error messages as part of the channel invalidation exception

src/main/java/net/snowflake/ingest/streaming/InsertValidationResponse.java, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/it/ColumnNamesIT.java
Validate if row contains null values for non-nullable columns. If yes, add such column names to InsertValidationResponse error as _NullValueForNotNullColNames_ so it can be used for schema evolution.
=> SNOW-1167007: Validate no null values for not null cols

.github/workflows/End2EndTest.yml, e2e-jar-test/core/pom.xml, e2e-jar-test/core/src/main/java/net/snowflake/IngestTestUtils.java, e2e-jar-test/fips/pom.xml, e2e-jar-test/fips/src/test/java/net/snowflake/FipsIngestE2ETest.java, e2e-jar-test/pom.xml, e2e-jar-test/run_e2e_jar_test.sh, e2e-jar-test/standard/pom.xml, e2e-jar-test/standard/src/test/java/net/snowflake/StandardIngestE2ETest.java, format.sh, pom.xml, src/main/java/net/snowflake/ingest/utils/Utils.java
This PR runs e2e jar tests with all LTS Java versions on all supported clouds. Compilation always happens with Java 8. The e2e jar test has been enhanced to test all supported data types. Additionally, this PR integrates google format with the e2e jar test project, so some changes lines are just reformats.
=> SNOW-1361785 Run e2e jar tests with multiple Java versions

pom.xml
Update to a newer version of fasterxml
=> No-SNOW Update fasterxml

pom.xml
This PR updates the vulnerable dependency `commons-configuration2`, which was found by Snyk.
This PR also upgrades some additional dependencies to satisfy the `RequireUpperBoundDeps` [rule](https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html) of the maven enforcer plugin.
=> SNOW-1262359 Upgrade commons-configuration2

src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java
Add error log for flush task scheduling. This could happen when [getCachedMaxClientLagInMs](https://github.com/snowflakedb/snowflake-ingest-java/blob/eb87281a6a1f5ee3e2e959594bb571b40b770b90/src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java#L268C65-L268C92) throw cast exception when provided parameter is `int` not `long`.
=> Add error log for flush task scheduling

README.md, e2e-jar-test/pom.xml, pom.xml, public_pom.xml
Updates JDBC driver to 3.16.1, which fixes regional AWS domain names in some regions. 
Related JDBC PR: https://github.com/snowflakedb/snowflake-jdbc/pull/1768
=> SNOW-1435061 Upgrade JDBC driver for domains fix

.github/workflows/End2EndTest.yml, e2e-jar-test/pom.xml, e2e-jar-test/run_e2e_jar_test.sh, pom.xml, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java
This PR parallelizes executions of e2e jar test across multiple GitHub Actions jobs. So far, test executions for shaded, unshaded and FIPS JARs with java 8, 11, 17 and 21 were all running in a single job. It is fine if the tests are quick, but before releases we additionally test long-running ingestion, which started timing out after 6 hours.
With this PR, we generate the build matrix of:
`[AWS, GCP, Azure] x [Java 8, 11, 17, 21] x [shaded, unshaded, fips]`
(in total 36 GitHub Action jobs)
=> no-snow Parallelize e2e jar tests

src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelsStatusRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
- Add requestId as a Query Parameter. 
- Remove requestId from payload since it is not used anywhere on server side. 
Along with this, our response should also include requestId but that can come later since they can still rely on offsetToken API. (Wont work for other APIs but there hasn't been any request)
This is for internal logging purposes.
=> SNOW-1357377 Add request Id in all streaming ingest APIs

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/MemoryInfoProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/MemoryInfoProviderFromRuntime.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
Here are the changes in order of high impact to low:
- Use pre-computed powers of 10 instead of computing it fresh for every insertRows call. 
- Periodically compute free memory in the system instead of on-demand.
- Use a for-loop instead of stream and collect in `verifyInputColumns`
- Cache numAvailableProcessors in FlushService.
- Cache parameters used in the hot path in `insertRows`.
I wrote a simple JMH benchmark to measure these changes - see `InsertRowsBenchmarkTest`. This benchmark inserts 1M rows in a tight loop and each row has a single sb16 column. Overall, 35-40% improvement in this benchmark observed. The benchmark results should carry over to real world workloads that have sb16 columns and the improvement in the memory tracking will transfer over to all workloads. 
Before: …
=> Various performance improvements in the `insertRows` path

pom.xml, scripts/process_licenses.py
- https://github.com/snowflakedb/snowflake-ingest-java/issues/778
- https://github.com/snowflakedb/snowflake-ingest-java/issues/777
- https://github.com/snowflakedb/snowflake-ingest-java/issues/776
=> SNOW-1457523: Upgrade Parquet dependencies version to fix CVE

src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/org/apache/parquet/hadoop/BdecParquetWriter.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java
This PR implements an additional safety check if the number of rows in the Parquet footer matches the number of metadata rows we've collected. If not, an internal exception is thrown.
=> SNOW-1465503 Check row count in Parquet footer before committing

src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestBigFilesIT.java
This PR fixes a flaky test, which is accessing `ArrayList` from multiple threads.
=> NO-SNOW Fix flaky test using multiple threads

src/main/java/net/snowflake/ingest/streaming/internal/StreamingIngestStage.java, src/main/java/net/snowflake/ingest/utils/ErrorCode.java, src/main/resources/net/snowflake/ingest/ingest_error_messages.properties, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestStageTest.java
This prevents issues when there is transparent failover using Client Redirect or another similar mechanism. Along the way, I found some missing/misconfigured error message resource and fixed them.
=> Reject new stage metadata if the deployment id does not match what the client was created with

src/main/java/net/snowflake/ingest/utils/HttpUtil.java
This PR reduces the timeout of waiting for a packet from 5 minutes to 1 minute. 5 minutes is too high, if there is a problem with the connection, it is better to give up earlier and retry.
=> SNOW-1512935 Reduce client socket timeout from 5 minutes to 1 minute

src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
We [previously](https://github.com/snowflakedb/snowflake-ingest-java/pull/730) increased the limits 4 times, which turned out to cause OOMs in some cases where memory is limited, so this PR reduces the limits by 1/2, which is still double of the original values. 
This PR also fixes a flaky test.
=> SNOW-1545879 Reduce the max channel/chunk sizes

src/main/java/net/snowflake/ingest/streaming/internal/ParquetChunkData.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
As part of the investigation for https://snowflakecomputing.atlassian.net/browse/SNOW-1506753 we discovered that the SDK has a concurrency issue when populating the `PRIMARY_FILE_ID_KEY` and there are concurrent uploads due to high load. 
In a nutshell, the problem is that the `ParquetRowBuffer#metadata` which is a map that contains some metadata that will be written as parquet metadata in the BDEC file, is shared across all uploading threads. So if one of those threads changes it, the others will see the changes. One of those metadata is also the  `PRIMARY_FILE_ID_KEY`.
=> SNOW-1618257 Fix PRIMARY_FILE_ID_KEY

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalParameterProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ManyTablesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/OAuthBasicTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
Split parameter `maxChunksInBlobAndRegistrationRequest` into `maxChunksInBlobs` and `maxChunksInRegistrationRequest`
Merging change of #763 and #773 into main branch.
=> SNOW-1483230 Parameter support & disable blob encryption for new table format

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetValueParser.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParquetValueParserTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/SemiStructuredIT.java
Currently, ingesting string JSON values into semi-structured types (i.e. `variant`, `object` and `array`), the SDK may modify the scientific notation of the input, i.e. convert values like `12.34` to `1.234e1` and vice versa. This PR makes sure the input format is preserved.
---
I micro-benchmarked parsing large json documents locally with JMH and the new approach also gives us ~50% speedup, it is likely due to the fact that we don't deserialize into the intermediate Jackson AST anymore:
```plain
NEW WAY
=======
Benchmark                              Mode  Cnt       Score       Error  Units
InsertRowsBenchmarkTest.testInsertRow  avgt   10  406466.888 ± 45677.292  us/op
OLD WAY
=======
Benchmark                              Mode  Cnt       Score       Error  Units …
```
=> SNOW-1566045 Preserve numeric format for variants

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetChunkData.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/org/apache/parquet/hadoop/BdecParquetReader.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsIT.java
- Write file name to metadata at the place when we create the file (only works for `serializeFromJavaObjects`)
- Looks like `serializeFromParquetWriteBuffers` is not maintained to work with `primaryFileId` as the `ParquetWriter` is created during `setupSchema`, we would better remove the code as a whole if we decide to not use it, or a bigger, separated change is required.
=> SNOW-1654124: Write file name to metadata at the place when we create the file

src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetChunkData.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
This PR removes `ENABLE_PARQUET_INTERNAL_BUFFERING`, which was an optimization we never enabled.
=> SNOW-1659373 cleanup serializeFromParquetBuffers

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
Also add sdk version to Parquet metadata.
=> Add chunk offset to file id key to make each chunk have a unique key

src/test/java/net/snowflake/ingest/streaming/internal/MockSnowflakeServiceClient.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeServiceClientTest.java
Moving code embedded inside SnowflakeServiceClientTest.java into a separate file with corresponding minor tweaks to make it work.
=> Carve out MockSnowflakeServiceClient to allow ExternalVolume tests in next PR to use it properly

pom.xml
The `com.google.protobuf:protobuf-java` and `org.apache.avro:avro` introduced in #814 failed the [Synk gate](https://app.snyk.io/org/snowflakedb-sca-scanning-public-repo/project/decdb8fe-6a6d-465d-9e89-84aa34efb781/history/59edc0f3-2ae9-407a-8e34-09de15fc5d5c). Upgrade packages to resolve it.
[JIRA](https://snowflakecomputing.atlassian.net/browse/SNOW-1674752)
=> SNOW-1674752 Fix vulnerable dependencies

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/MockSnowflakeServiceClient.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
As part of bringing in ExternalVolume (presigned url based uploads), I decided to not add test-only code into ExtVol / ExtVolManager. This meant the following:
1. All the httpClient mock logic to return hardcoded responses now needs to handle multiple APIs (client configure AND getPresignedUrls) - this looked very similar to MockSnowflakeServiceClient logic but duplicated 10 times.
2. To fix this, introduced a per-API behavior override mechanism in MockSNowflakeServiceClient; helped me remove hundreds of lines of code that was just setting up the httpclient mock, and reduce how brittle that setup is
3. To do away with isTestMode in InternalStage / InternalStageManager, also did the following two changes:
1. Make the snowflake service client respond to telemetry upload calls correctly when …
=> Get test coverage for telemetry reporting (was missing) + Fix SnowflakeServiceClient test code to allow per-API overrides 

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/DropChannelRequestInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeServiceClientTest.java
1. Set createdOn on the blob Metadata, which can be used in the service to populate the FileRegistrationRequest
2. Set is_iceberg in /channels/drop API payload since it gets validated the same way as open channel (where we do have the is_iceberg API available)
=> Set createdon in BlobMetadata and is_iceberg in Drop Channel request

src/main/java/net/snowflake/ingest/streaming/internal/ExternalVolume.java, src/main/java/net/snowflake/ingest/streaming/internal/GeneratePresignedUrlsResponse.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/ExternalVolumeManagerTest.java, src/test/java/net/snowflake/ingest/streaming/internal/MockSnowflakeServiceClient.java
1. Only use a URL if its more than 1 minute away from expiry
2. Handle a nullref in ExternalVolume.generateUrls
3. In case of high concurrent load on the url generation semaphore, only wait to acquire when the queue is null. If this was an optimistic URL fetch there is no need to wait around or the semaphore.
4. fix comment line wrapping.
5. add concurrent test for the generateUrl changes
6. TODO add test for the "dont use urls that are about to expire in the next minute" logic
=> Fix concurrent null-ref in External Volume Blob path Generation + track URL timeout

src/test/java/net/snowflake/ingest/TestUtils.java
TestUtils has four unexpected behaviors:
1. When there is no profile.json available, we do keypair generation many many times in every testcase instead of doing it once. Fixed this.
2. The no-profile-json code path ends up hitting snowflake.qa1.int.snowflakecomputing.com from unit tests (should be hitting a mock)
3. If a profile.json is being used for local testing, all unit tests start using it too because TestUtils ends up reading the same profile.json. This is highly unexpected.
4. Profile.json parsing behavior between prod and test codepaths is different. the former is okay with just the URL being specified, the latter forces specification of scheme, host, port, ssl.
Fixing (1) with this PR.
=> Fix testUtils to not repeatedly do keypair generation

src/main/java/net/snowflake/ingest/streaming/internal/ColumnProperties.java
For schema evolution of structured data types, Kafka Connector needs a way to discover the schema of the column that had a validation error.
We already have an API on StreamingIngestChannel called getTableSchema() that returns a Map<String, ColumnProperties>.
Am adding a method (currently non-public) to the ColumnProperties type called getIcebergSchema() that returns a spec-compliant JSON of the column's iceberg schema.
We'll make this method public when we make setIsIceberg() public.
=> Add (non-public) method to expose iceberg schema for each column of a channel

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/FileColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalParameterProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
1. Remove hidden polymorphic behavior of RowBufferStats, 
2. remove isIceberg
3. Refactoring in FileColumnProperties - @sfc-gh-alhuang For strings, i see that there is a truncateUp for the Max stat and 
truncateDown for min stat. Please reivew this part carefully and compare with what it used to be before we started making changes, want to make sure we aren't regressing FDNs on this front.
Note that this is a stacked PR.
=> Fixes identified during code review

pom.xml
I think we don't need the avro dependency and can exclude it to resolve 
https://github.com/snowflakedb/snowflake-ingest-java/issues/853
An alternative is upgrading to 1.6.1 iceberg-core, which has avro version 1.12.0 but if we confirm that we don't need it, it's best to exclude
=> SNOW-1711460 Exclude avro dependency to fix 853

pom.xml
Revert due to usage in kafka connector.
Waiting for newer release of iceberg-core before we can address https://github.com/snowflakedb/snowflake-ingest-java/issues/853
As the latest iceberg-core version does not include an upgrade avro dependency
=> REVERT SNOW-1711460 Exclude avro dependency to fix 853

src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/ChannelFlushContext.java, src/main/java/net/snowflake/ingest/streaming/internal/OpenChannelResponse.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
Took the liberty of sending out a PR instead of describing what I had in mind textually.
1. Remove logic from OpenChannelResponse contract class
2. Move writerVersion defaulting to channel construction callsite in clientInternal (from channel ctor), instead of passing writerVersion=null into the channel.
3. Pass around writerVersion via RowBuffer into Flusher, instead of via the per-chunk flushContext.
4. Remove a test-only overload of ChannelInternal
5. Remove an unnecessary parameter on ChannelInternal ctor (bdecVersion)
6. Remove SerializationPolicy.NON_ICEBERG, remove the custom SerPolicy.fromName method and use Enum.valueOf that java already has
Once the merge gates are green, will merge this into the V2 PR.
=> (Stacked PR) Code review changes for Parquet V2

src/main/java/net/snowflake/ingest/streaming/internal/BlobPath.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/IStorageManager.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalStage.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalStageManager.java, src/main/java/net/snowflake/ingest/streaming/internal/PresignedUrlExternalVolume.java, src/main/java/net/snowflake/ingest/streaming/internal/PresignedUrlExternalVolumeManager.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InternalStageTest.java, src/test/java/net/snowflake/ingest/streaming/internal/PresignedUrlPresignedUrlExternalVolumeManagerTest.java
1. Rename ExternalVolumeManager --> PresignedUrlExternalVolumeManager
2. Rename ExternalVolume --> PresignedUrlExternalVolume
3. Change BlobPath field names from filename/url (which were still pretty ambiguous) to fileRegistrationPath / uploadPath.
This PR does not introduce any logical changes, and is preparing the brach for the next (stacked) PR that actually brings in a subscoped token based external volume manager.
=> SNOW-1754295 - Prep for upcoming subscoped tokens PR

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/IcebergDataTypeParser.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergNumericTypesIT.java
This PR addresses the issue where the scanner encounters an error when scanning delta-encoded decimal values with a precision greater than 18.
1. Removed `sfVer` metadata in Iceberg mode: This prevents the scanner from applying optimizations specific to Snowflake-written Parquet files, which was the root cause of the issue with scanning.
2. Add tests for multiple random generated decimals.
=> SNOW-1748333 Fix Iceberg decimal type schema parser

src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
Fix date time integration test for Iceberg. Use string compare to avoid time zone difference.
=> Fix Iceberg DateTimeIT

src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java, src/main/java/net/snowflake/ingest/streaming/internal/RowBufferStats.java, src/main/java/org/apache/parquet/hadoop/SnowflakeParquetWriter.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferStatsTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java
This PR includes following changes:
1. Fix empty list & map ingestion.
2. Added test for empty list & map. 
3. Removed assert exception for nested type as the EP key fix should be available on prepod now.
=> Fix empty map & list ingestion

src/main/java/net/snowflake/ingest/streaming/SnowflakeStreamingIngestClientFactory.java, src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/ColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/DropChannelRequestInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/GeneratePresignedUrlsRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalParameterProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/OpenChannelRequestInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/RefreshTableInformationRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterBlobRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/OAuthBasicTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RequestSerializationTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeServiceClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java
The PR includes following changes:
1. Remove `setIceberg` from `StreamingIngestClientFactory`, set Iceberg mode from properties.
2. Renamed `isIceberg` to `enableIcebergStreaming`.
=> SNOW-1760732 Enable Iceberg mode from properties

src/main/java/net/snowflake/ingest/streaming/internal/ClientBufferParameters.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
Update `primaryFileId` to `assignedFullFileName` in metadata when streaming to Iceberg table.
=> SNOW-1774276 Update fileId key in metadata for Iceberg mode

pom.xml, src/main/java/net/snowflake/ingest/connection/RequestBuilder.java, src/main/java/net/snowflake/ingest/connection/TelemetryService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/connection/TelemetryServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelCacheTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/InsertRowsBenchmarkTest.java, src/test/java/net/snowflake/ingest/streaming/internal/MockSnowflakeServiceClient.java, src/test/java/net/snowflake/ingest/streaming/internal/OAuthBasicTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeServiceClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsIT.java, src/test/java/net/snowflake/ingest/streaming/internal/SubscopedTokenExternalVolumeManagerTest.java
adding the enableIcebergStreaming boolean flag to all telemetry service calls done by the SDK.
Marking many of the RequestBuilder ctors as Deprecated.
=> Add enableIcebergStreaming to telemetry calls

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetTypeGenerator.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeParquetValueParser.java, src/main/resources/net/snowflake/ingest/ingest_error_messages.properties, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeParquetValueParserTest.java
Many of the data validation error messages were lacking information around (a) which column the offending value was in, and (b) what was the offending value.
Took a pass at all the validation errors (INVALID_VALUE_ROW, INVALID_FORMAT_ROW, UNKNOWN_DATA_TYPE) and fixed them up.
=> Enhance error messages in the SDK

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/IcebergDataTypeParser.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/it/ColumnNamesIT.java
For non-structured data type column, server sides perform EP info check which requires the column display name to be exactly the same as the quoted column name. Fix a bug on this and extend existing column name test to run on iceberg as in preprod as well. Disable the Iceberg test now the pass the merge gate.
=> Fix quoted column name for Iceberg primitive type

pom.xml
AVRO CVE is a false alarm and does not affect this dependency so we will keep using Iceberg 1.6.1 due to java 8 support 
CVE does not affect Iceberg: https://www.mail-archive.com/dev@iceberg.apache.org/msg07864.html
=> [SNOW-1711460] Upgrade to iceberg version 1.6.1

src/main/java/net/snowflake/ingest/streaming/InsertValidationResponse.java, src/main/java/net/snowflake/ingest/streaming/internal/AbstractRowBuffer.java, src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/main/java/net/snowflake/ingest/utils/SubColumnFinder.java, src/test/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParserTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java
Currently the `InsertError` doesn't populate extra columns, missing columns, null value for non null columns in `InsertValidationResponse` when ingesting structured data type to Iceberg tables. The PR is fixing this.
We use parquet dot path with escaping dot and back slash character in field name to represent sub-columns. For example, column `x` in `map_col(string, object("a.b" array(object("c\d" object(x int)))))` has a path `MAP_COL.key_value.value.a\.b.list.element.c\\d.x`
=> SNOW-1787322 Fix InsertError for structured data type

src/test/java/net/snowflake/ingest/TestUtils.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/BinaryIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/DateTimeIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergDateTimeIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergLogicalTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergNumericTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStringIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/LogicalTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/NullIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/NumericTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/SemiStructuredIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/StringsIT.java, src/test/java/net/snowflake/ingest/streaming/internal/it/ColumnNamesITBase.java, src/test/java/net/snowflake/ingest/streaming/internal/it/FdnColumnNamesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergColumnNamesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/it/ManyTablesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/it/StreamingIngestBigFilesIT.java
Enable ColumnNamesIT for Iceberg mode. Split into two test classes as we are planning adding test group for Iceberg/non-Iceberg ITs.
=> Enable ColumNamesIT for Iceberg mode

.github/workflows/End2EndTest.yml, pom.xml, scripts/run_gh_actions.sh, src/test/java/net/snowflake/ingest/IcebergIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergDateTimeIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergLogicalTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergNumericTypesIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStringIT.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java, src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergColumnNamesIT.java
Setup merge gates for Iceberg streaming. For now we only supports AWS. Disabled a string test, will add it back after SNOW-1798403 is fixed.
=> Introduce Iceberg streaming merge gate

src/test/java/net/snowflake/ingest/streaming/internal/datatypes/AbstractDataTypeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergSchemaEvolutionIT.java
Add a schema evolution test for Iceberg ingestion. Will add one for structured data type after #869 is merge as that PR includes logic for object comparison.
=> Schema evolution test for Iceberg ingestion

src/main/java/net/snowflake/ingest/streaming/internal/ParquetRowBuffer.java, src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergSchemaEvolutionIT.java
Fix the error when the column ordinal of structured data is out of order. The logic used to assume that the root columns are the first k smallest of whole schema, which is incorrect after schema evolution. Add a map for column ordinal to column to fix this.
=> SNOW-1806157 Fix field id mismatch during schema evolution for structured data type

src/main/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParser.java, src/test/java/net/snowflake/ingest/streaming/internal/datatypes/IcebergStructuredIT.java
The original logic didn't calculate null count for missing fields, fix this.
=> SNOW-1808626 Fix struct type statistic for missing fields

src/main/java/net/snowflake/ingest/streaming/internal/BlobPath.java, src/main/java/net/snowflake/ingest/streaming/internal/ColumnProperties.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalParameterProvider.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SubscopedTokenExternalVolumeManager.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ChannelDataTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FileColumnPropertiesTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/IcebergParquetValueParserTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferStatsTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
- logging fixes
- make api public for schema evolution in KC
- stop ndv tracking since its causing ingestion to massively slow down.
=> Make Channel.getIcebergSchema() API public + Stop NDV tracking

src/main/java/net/snowflake/ingest/streaming/internal/InternalStage.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterBlobRequest.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java
Iceberg's billing needs the clientname and clientkey at the time of DML Commit. While it can be read via a S3 get-metadata call, its a wasteful approach. This PR optimizes away that S3 call by sending the metadata inline with the registerBlobs API call.
Ran FDN and Iceberg ITs locally against sfctest0 to make sure the json backcompat fix from months ago will allow unknown fields to appear on the payload without causing issues. IT run from this PR's merge gate should be green.
=> Send clientname and clientkey with every registerblobs request for metering views

src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/DataValidationUtilTest.java
The SDK should not ingest the variant like {"key": 1, "key": 2} otherwise, we would have issues in the XP during select and there is no good mitigation on that.
In this change, we would error out with INVALID_VALUE_ROW for such duplicate cases.
Added Unit test for the change.
=> [SNOW-1882616] Error out for duplicate keys in variant

src/test/java/net/snowflake/ingest/streaming/internal/InternalStageTest.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestIT.java
The `InternalStageTest` didn't clean up the proxy after test which cause some Jenkins jobs failed to fetch package afterwards. Clean up proxy to make it work.
=> Clean up proxy after unit tests

src/main/java/net/snowflake/ingest/SimpleIngestManager.java
Merging pr from @nirutgupta
https://github.com/snowflakedb/snowflake-ingest-java/pull/930
The CloseableHttpResponse is closed with try catch ([ref](https://github.com/snowflakedb/snowflake-ingest-java/blob/v3.0.1/src/main/java/net/snowflake/ingest/SimpleIngestManager.java#L532)), but the client itself is not getting closed, in case if exception is thrown [here](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java#L122). This is causing connection leaks, timeout errors and decrease in throughput.
Added the fix to close the httpClient in SimpleIngestManager close() method.
Will add ingestManager.close() [here](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java …
=> close httpClient when closing simpleIngestManager 

src/main/java/net/snowflake/ingest/streaming/internal/BlobBuilder.java, src/main/java/net/snowflake/ingest/streaming/internal/FileMetadataTestingOverrides.java, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/Flusher.java, src/main/java/net/snowflake/ingest/streaming/internal/ParquetFlusher.java, src/test/java/net/snowflake/ingest/streaming/internal/BlobBuilderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RowBufferTest.java
The primary reason for this PR is to allow passing a custom fileId for testing PPN behavior in Snowflake. This unblocks migrating some tests to Snowfort.
=> allow passing custom metadata to `ParquetFlusher` for testing

src/main/java/net/snowflake/ingest/SimpleIngestManager.java
We are revering this (recent) change because it was reported to cause regressions to our Kafka Connector. For a discussion see https://snow-external.slack.com/archives/C02282DHC7K/p1739772667115639 (private channel but reviewers must have access).
cc @sfc-gh-xhuang @sfc-gh-tzhang
=> Revert of df6bc9e85b2fd872d912bff5c47571ed237737ec

src/main/java/net/snowflake/ingest/streaming/internal/InternalStage.java
This PR takes advantage of a new feature in JDBC driver 3.22.0, which lets us silence exception log in the JDBC driver in case an upload fails.
=> SNOW-1881734 Silence uploadWithoutConnection exception log

src/main/java/net/snowflake/ingest/connection/OAuthClient.java, src/main/java/net/snowflake/ingest/connection/OAuthManager.java, src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/connection/MockOAuthClient.java
Decoupled the HTTP client for streaming and authentication, as the SDK previously used a single client for both streaming ingestion and OAuth authentication. This change ensures compliance with the customer's requirement to configure separate proxy settings for streaming and authentication.
=> SNOW-1947905 Fix proxy setting for OAuth http client

deploy.sh
There has been a connection error during the release of snowflake-ingest-java. The last 3 releases, including unshaded, had this issue. 
Last time, shaded version was released skipping tests to unblock the release. The error is something like this:
```
00:11:41.344 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar (default-jar) on project snowflake-ingest-sdk: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar failed: Plugin org.apache.maven.plugins:maven-jar-plugin:2.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-jar-plugin:jar:2.4 -> org.apache.maven:maven-archiver:jar:2.5: Failed to read artifact descriptor for org.apache.maven:maven-archiver:jar:2.5: Could …
```
=> SNOW-1983454: Download required dependencies before release

unshaded_deploy.sh
There has been a connection error during the release of snowflake-ingest-java. The last 3 releases, including unshaded, had this issue.
Unshaded version was released using this code and confirmed on shaded version 3.1.2.
```
00:10:29.184 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar (default-jar) on project snowflake-ingest-sdk: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar failed: Plugin org.apache.maven.plugins:maven-jar-plugin:2.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-jar-plugin:jar:2.4 -> org.apache.maven:maven-archiver:jar:2.5: Failed to read artifact descriptor for org.apache.maven:maven-archiver:jar:2.5: Could not transfer artifact …
```
=> SNOW-1983454: Download required dependencies before release for unshaded version

.github/workflows/End2EndTest.yml, scripts/update_project_version.py
Our Github action merge gate keeps failing starting from yesterday due to several errors, this PR fix it.
* Upgrade to `ubuntu-24.04` as the old `ubuntu-20.04` is not supported anymore from yesterday. https://github.com/actions/runner-images/issues/11101
* Upgrade `upgdate_project_version.py` to run in python3. The python2 is not preinstalled in ubuntu 24.04, and cannot be installed via `setup-python` due to python2's deprecation. https://github.com/actions/setup-python/issues/672. Note that this change makes the original comments in `public_pom.xml` unavailable but this doesn't affect the testing results. 
* Upgrade `setup-java@v2` to `setup-java@v4` and specify `cache-dependency-path` as there seems to be some problem with maven caching service on `setup-java@v2` using `action/cache@v3` …
=> NO-SNOW Fix merge gate

src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergOpenChannelIT.java
Added an end-to-end test to verify that using the streaming SDK on a partitioned table yields a clear user-facing error. Tested on preprod and qa with `ENABLE_FIX_1633616_ALLOW_ROLLOUT_PARTITIONED_ICEBERG` set. Disabled in prod for now, will enable after `ENABLE_FIX_1633616_ALLOW_ROLLOUT_PARTITIONED_ICEBERG` is rollout.
=> SNOW-1903895 Add end-to-end test for disabled streaming on partitioned table

src/main/java/net/snowflake/ingest/utils/HttpUtil.java, src/test/java/net/snowflake/ingest/streaming/internal/StreamingIngestUtilsTest.java, src/test/java/net/snowflake/ingest/utils/HttpUtilTest.java
Specifically for channelsOpen API, we see the following flow:
1. API handler calls [executeWithRetries()](https://github.com/snowflakedb/snowflake-ingest-java/blob/1cd64137219da10e001b61aa32d509a9f445704c/src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeServiceClient.java#L236), which makes the HTTP call and extracts the response
2. HTTP client uses [getServiceUnavailableRetryStrategy()](https://github.com/snowflakedb/snowflake-ingest-java/blob/1cd64137219da10e001b61aa32d509a9f445704c/src/main/java/net/snowflake/ingest/utils/HttpUtil.java#L227-L280) to determine when to retry server errors
The confusion is that step 1 contains [logic to retry internal code `GENERAL_EXCEPTION_RETRY_REQUEST`](https://github.com/snowflakedb/snowflake-ingest-java/blob/1cd64137219da10e001b61aa32d5 …
=> [SNOW-2134338] Add unit tests for http client retry strategy

.github/workflows/End2EndTest.yml, pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/FlushService.java, src/main/java/net/snowflake/ingest/streaming/internal/RegisterService.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java, src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/main/java/net/snowflake/ingest/utils/Constants.java, src/main/java/net/snowflake/ingest/utils/ParameterProvider.java, src/test/java/net/snowflake/ingest/streaming/internal/FlushServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/ParameterProviderTest.java, src/test/java/net/snowflake/ingest/streaming/internal/RegisterServiceTest.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTest.java
We have seen the issue in the O11y case when the chunk queue is full, channel write starts return QUEUE_FULL error, and it causes the channel to be invalidated. Channel invalidation results in a new set of channel reopen, which makes the issue even worse. 
With this PR:
- We will keep retrying on QUEUE_FULL up to roughly 5mins instead of just a few seconds before invalidating the channel.
- Add a limit on the registration queue and throttle insertRows once it reaches a certain size
- Both parameters are configurable in case there is any regressions.
=> SNOW-2174149: Keep retrying on QUEUE_FULL instead of invalidating channels

src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientInternal.java, src/test/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestClientTmkRefreshTest.java
This PR updates the table key in the per-table key map during channel open. The previous code was only updating the client key storage only when server-side TMK refresh is initiated during enqueue.
=> SNOW-2205584 Refresh TMK in client on channel reopen

unshaded_deploy.sh
Remove `-unshaded` suffix from the version in the unshaded deployment script.
Generated POM will have the correct version: 4.2.0-unshaded (not the double-suffixed version)
=> NO-SNOW Fix 4.2.0 unshaded release

pom.xml, src/main/java/net/snowflake/ingest/streaming/internal/FileLocationInfo.java
Upgraded Snowflake JDBC driver to version 3.25.1 and added GCS virtual URL support for SCPS.
- Updated the Snowflake JDBC driver version from 3.24.2 to 3.25.1 in pom.xml
- Added a new `useVirtualUrl` boolean field to pass to JDBC file transfer agent.
- Updated Jacoco to make it compatible with JDBC driver.
- Only include project code for coverage analysis.
=> FLOW-4820 Openflow x SPCS x GCP support

unshaded_deploy.sh, unshaded_snapshot_deploy.sh
Updated deployment scripts to use the main pom.xml instead of public_pom.xml for version updates.
Modified both `unshaded_deploy.sh` and `unshaded_snapshot_deploy.sh` to use the main `pom.xml` file as input for the `update_project_version.py` script instead of `public_pom.xml`. Also removed the `-unshaded` suffix from the version in the snapshot deployment script.
=> NO-SNOW Fix v4.2.0 unshaded pom.xml

src/main/java/net/snowflake/ingest/streaming/internal/FileLocationInfo.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalStage.java, src/main/java/net/snowflake/ingest/streaming/internal/InternalStageManager.java, src/main/java/net/snowflake/ingest/streaming/internal/VolumeEncryptionMode.java, src/main/java/net/snowflake/ingest/streaming/internal/fileTransferAgent/IcebergFileTransferAgent.java, src/main/java/net/snowflake/ingest/streaming/internal/fileTransferAgent/IcebergGCSClient.java, src/main/java/net/snowflake/ingest/streaming/internal/fileTransferAgent/IcebergS3Client.java, src/main/java/net/snowflake/ingest/streaming/internal/fileTransferAgent/IcebergStorageClientFactory.java, src/test/java/net/snowflake/ingest/streaming/internal/InternalStageTest.java, src/test/java/net/snowflake/ingest/streaming/internal/VolumeEncryptionModeTest.java, src/test/java/net/snowflake/ingest/streaming/internal/it/IcebergKmsEncryptionIT.java
Support server side KMS encryption when uploading the file to external volume on AWS and GCP.
An encryption option can be specified on an external volume on top of a storage bucket. However, SSV1 Iceberg ingestion does not honor the option value because AES_256_SERVER_SIDE_ENCRYPTION (SSE_S3) is hardcoded in the SDK code.
=> SNOW-2302576 Honor the encryption option set on the external volume
